import Foundation

/// The Grappa client token that AirTraffic's sync requires.
///
/// ## Why this file exists
///
/// The ATC daemon on iOS 27 will not accept a sync without a Grappa blob in
/// `HostInfo/RequestingSync`. `airlift_ffi` does not build one: it resolves a
/// symbol out of the running app and calls it
/// (`rust-core/src/grappa.rs`), which is why every AirLift write used to fail
/// with
///
///     airlift: grappa: ALGetGrappaToken symbol not found
///     airlift: atc sync state for '…': 'SyncFailed'   (ErrorCode 4)
///
/// — the tunnel came up, the files were enumerated, the capabilities were
/// negotiated, and then the first write was refused for want of a token. The
/// ported reference carries `ios-app/GrappaHelper.m` for exactly this reason and
/// it had not been ported here; this is that file.
///
/// ## Why there is no private-framework call in here
///
/// A Grappa blob is an opaque CoreFP session-negotiation artefact, not a key,
/// and it is generated by Apple's private AirTraffic frameworks. The reference
/// tries to generate one at runtime and, in the same function, keeps a table of
/// authentic blobs captured from a real generation. On iOS there is no CoreFP, so
/// the generation half of that cannot succeed here — the reference's own
/// fallback is to hand the daemon a blob from the table, and that is the path
/// the daemon accepts.
///
/// So this returns a table entry and nothing else. The generation path is not
/// merely unnecessary, it is unreachable-in-practice *and* unreachable-safely:
/// it is Objective-C message sends to a class that does not exist at compile
/// time, and a selector the private class does not implement raises
/// `NSException`, which the reference catches with `@try` and Swift cannot catch
/// at all. A first port of this that attempted those calls took the app down on
/// launch, which is worse than the `SyncFailed` it was meant to fix.
///
/// ## Why it is Swift
///
/// A SwiftPM target may not mix Swift and Objective-C, this app target is
/// Swift-only, and `scripts/sync-pbxproj-sources.py` mirrors `.swift` files into
/// the Xcode project. A second C/ObjC target would have meant a new product in
/// `Package.swift`, build files in three places, and a second linkage path for
/// one function. The C symbol is exported with `@_cdecl` instead, under exactly
/// the spelling `dlsym` looks for.
///
/// ## Keeping it in the binary
///
/// Defining the function is not enough. Nothing references it, so the linker
/// dead-strips it and the `dlsym` fails anyway — the same `SyncFailed`, now with
/// a symbol that is visibly present in the object file and absent from the
/// executable. `Airlift.installGrappaTokenProvider()` calls it at launch, which
/// both pins the symbol and reports the answer before a user presses Apply.
enum GrappaToken {
    /// The `(version: 1, deviceType: 0, protocolVersion: 1)` blob the daemon
    /// announces in `GrappaSupportInfo` and the FFI passes in.
    ///
    /// The reference tries each table entry against the device's own
    /// `ATGrappaSession` and keeps the first that answers; on iOS none of them
    /// answer, and the first candidate is what its fallback keeps — which is
    /// what the daemon then accepts.
    static let token = Data(hexString: authenticTokens[0]) ?? Data()

    /// Whether this process can hand `airlift_ffi` a token.
    ///
    /// `0` when it can. The negative codes are the reference's, kept so a log
    /// line means the same thing here as it does there: -1 invalid output
    /// buffer, -2 AirTraffic could not be loaded, -3 `ATGrappaSession` is not in
    /// the runtime, -5 no token, -6 the token does not fit in `maxLength`, -99 an
    /// Objective-C exception.
    static func status() -> Int32 {
        probe().status
    }

    /// The length the FFI will be handed, or 0 if there is no token.
    static func previewLength() -> Int {
        probe().length
    }

    /// One real call to the C entry point, reporting what came back.
    ///
    /// This is what keeps `_ALGetGrappaToken` alive — see the type comment.
    private static func probe() -> (status: Int32, length: Int) {
        var buffer = [UInt8](repeating: 0, count: 512)
        var length = 0
        var error = [CChar](repeating: 0, count: 256)
        let status = buffer.withUnsafeMutableBufferPointer { out in
            error.withUnsafeMutableBufferPointer { message in
                alGetGrappaToken(1, 0, 1,
                                 out.baseAddress, out.count,
                                 &length,
                                 message.baseAddress, message.count)
            }
        }
        return (status, status == 0 ? length : 0)
    }
}

/// `ALGetGrappaToken` — the C symbol `airlift_ffi` resolves with
/// `dlsym(RTLD_DEFAULT, "ALGetGrappaToken")`; see `rust-core/src/grappa.rs`
/// for that side and the reference's `ios-app/GrappaHelper.h` for this
/// signature.
///
/// The three version arguments are the daemon's `GrappaSupportInfo`, which is
/// `(1, 0, 1)` on the device this runs against. A request for anything else is
/// answered from the same table, as the reference's fallback does — the blobs
/// are not parameterised by those values, they were all captured for `(1, 0, 1)`.
///
/// - Parameters:
///   - inVersion: Grappa `version`; 0 is taken as 1.
///   - inDeviceType: Grappa `deviceType`; unused, kept for signature parity.
///   - inProtocolVersion: Grappa `protocolVersion`; 0 is taken as 1.
///   - outBuffer: receives the token. Must be non-nil and at least one byte.
///   - maxLength: capacity of `outBuffer`.
///   - outLength: receives the token's length.
///   - errorBuffer: receives a NUL-terminated message, if there is one.
///   - errorLength: capacity of `errorBuffer`.
/// - Returns: 0 on success, or a negative code; see `GrappaToken.status()`.
@_cdecl("ALGetGrappaToken")
public func alGetGrappaToken(
    _ inVersion: UInt32,
    _ inDeviceType: UInt32,
    _ inProtocolVersion: UInt32,
    _ outBuffer: UnsafeMutablePointer<UInt8>?,
    _ maxLength: Int,
    _ outLength: UnsafeMutablePointer<Int>?,
    _ errorBuffer: UnsafeMutablePointer<CChar>?,
    _ errorLength: Int
) -> Int32 {
    let token = GrappaToken.token

    guard let outBuffer, maxLength > 0 else {
        GrappaToken.fail("invalid output buffer", errorBuffer, errorLength)
        return -1
    }
    guard !token.isEmpty else {
        GrappaToken.fail("failed to obtain valid Grappa token", errorBuffer, errorLength)
        return -5
    }
    guard token.count <= maxLength else {
        GrappaToken.fail("buffer too small: \(token.count) > \(maxLength)", errorBuffer, errorLength)
        return -6
    }

    token.withUnsafeBytes { raw in
        if let base = raw.baseAddress {
            outBuffer.update(from: base.assumingMemoryBound(to: UInt8.self), count: token.count)
        }
    }
    outLength?.pointee = token.count
    return 0
}

extension GrappaToken {
    /// Copies a message into the caller's error buffer, truncated to leave room
    /// for the terminator: the FFI reads this with `CStr::from_ptr`, so a full
    /// buffer with no NUL would read past its end.
    static func fail(_ message: String,
                     _ errorBuffer: UnsafeMutablePointer<CChar>?,
                     _ errorLength: Int) {
        guard let errorBuffer, errorLength > 0 else { return }
        var bytes = Array(message.utf8.prefix(errorLength - 1))
        bytes.append(0)
        errorBuffer.withMemoryRebound(to: UInt8.self, capacity: errorLength) { destination in
            bytes.withUnsafeBytes { source in
                guard let start = source.baseAddress else { return }
                destination.update(from: start.assumingMemoryBound(to: UInt8.self), count: bytes.count)
            }
        }
    }
}

private extension Data {
    /// Hex to bytes, or nil on a malformed string.
    init?(hexString: String) {
        let chars = Array(hexString)
        guard chars.count % 2 == 0 else { return nil }
        var bytes = [UInt8]()
        bytes.reserveCapacity(chars.count / 2)
        for index in stride(from: 0, to: chars.count, by: 2) {
            guard let byte = UInt8(String(chars[index...index + 1]), radix: 16) else { return nil }
            bytes.append(byte)
        }
        self.init(bytes)
    }
}

/// Authentic Grappa client request blobs, generated by Apple's CoreFP for
/// `(version: 1, deviceType: 0, protocolVersion: 1)`.
///
/// The reference's table, unmodified and in order: entry 0 is the one its
/// fallback hands over when no candidate verifies, and the one this returns.
private let authenticTokens = [
    "01012ba6a01f2ccf66a02613d5b72e0bc916004058a001a6874d18b5bd7b3395e25d79fa3ffcc67e718106d485c51540b828d1620e9f94f582d3bcc6f97e9088c923095ad8d36ab568fb45df61e286d25354b04c",
    "0101efa33b1586f410087474b2ccaf8cdb4d0040e5aee6017fdcf774a51c1980b4238076e86218af5a5f169470df90b73f4fc893a22da94fb9745c10f23df0620cfe3f19be3f2ab37d2f7590d8597ab51ebcced0",
    "0101aab479a6d8226f3e1d7a57a2501337e50240e54444b5f1d04101205a7a2f3d148d18440e2edef03d37fcdc7423c0bb441b4c4a355169d511d67ae3466fdf8865e69a8aed45867801ea8e1bbb48889ba0b834",
    "010194ab2ece86e05d7313e4075a947ab3be0240c9237c46b3c519d2ec297304413dab741827016e5eb9af8792bc2b3d6f12be25397931f41bffb887d042b97057c03ed8d72a3acb72378d30f7a073e3d7590f62",
    "01018cec0ea2c25446c90133d435eaafb0150240c6c28dd42f62f8907133c462fc8b6def05e543ab2d59952f6eb3b38e382d492cd2881beceaeaea67fc1331f77fca50fde6bed35622009670e6d6e4a36b09c088",
    "0101243b2587f14dd812751c6710730f46d50440fe2e5e9ccfe70200487e14c131412381fd7c214241b182ca04ebe0c1f3cdd54ac17eef31705c06289e02f672fa8c0d9dff167f1c925df876d5814d3265f55b06",
    "01016f8908f8f972bdc8fe99002f7648e86c024011a469c4320bb7e44137756dde3ecfbff08a55081e532c12a06101c6ae5283a014512d977eafad06c34b1f116422f6bf72ef56f8d734d37db287b170be7a3a82",
    "01015c5fcc103d0460f5bbfd48c387806e8e0340e3323ed780fbeccc2908c059d9a81e75976bf058b411f62a9a6e1df7ba307f69226942373f484690799b230bc60e99036f40eae25229aff6bb31ab74820e68a9",
    "0101f3f542aaa17252a8f81b3dc5b007adc304408d2496cee3af54113ffa9fba392b4143d4c38e4d79680e8e9feb554e450c1f89220c02375a9063b3a62bf61f62bd073991ebf215c6c2e28938d1aa53ed580c02",
    "0101fc26f7e89d1635d86b5c886df69f526a0040038b6c33049f6bd5cc526b4ee7ccce614135d2c73f8326d9af6d28399a231510917493d4fdaa395b4d1c1e1b09bdf3fe6fb7e16ad6d5f5cc18b93730874e6f4e",
]
