// Generated by scripts/gen-pb-resources-from-goldennugget.py — do not edit by hand.
//
// Source: the reference's ``files/posterboard``, 20 files,
// 17854 bytes, embedded base64.  These are the files the reference reads through
// ``get_bundle_files("files/posterboard/…")``.
//
// Embedded rather than shipped as bundle resources on purpose: this project is
// built by both Xcode (from project.pbxproj) and xtool (from xtool.yml), and a
// resource added to only one of them would produce two bundles that quietly
// disagree.  A generated Swift file cannot be half-installed.
//
// Regenerate after an upstream change to that directory; `--check` fails on drift.

import Foundation

enum PosterBoardResources {
    /// Base64 decoding that tolerates the line wrapping above, and refuses to
    /// hand out an empty file where a real one was written: a corrupt literal
    /// would otherwise reach the device as a 0-byte payload, which the wallpaper
    /// store answers by dropping the descriptor.
    private static func b64(_ value: String) -> Data {
        guard let data = Data(base64Encoded: value, options: .ignoreUnknownCharacters),
              !data.isEmpty || value.isEmpty else {
            preconditionFailure("PosterBoardResources: a base64 literal did not decode")
        }
        return data
    }

    /// The live-photo descriptor root's own name.  ``create_live_photo_files``
    /// writes the video into a folder of this name under ``video-descriptor/``.
    static let livePhotoIdentifier = "1F20C883-EA98-4CCE-9923-0C9A01359721"

    /// The three ``com.apple.posterkit.provider.instance.*`` plists that replace a tendie's
    /// own copies (``PBConfigManager.cache_config_files``).
    static let configConversion: [String: Data] = [
        "com.apple.posterkit.provider.instance.quickActions.plist":
            b64("""
            YnBsaXN0MDDUAQIDBAUGBwpYJHZlcnNpb25ZJGFyY2hpdmVyVCR0b3BYJG9iamVjdHMSAAGGoF8QD05TS2V5ZWRBcmNoaXZl
            ctEICVRyb290gAGvEBILDBMbIyssLTQ1OT1BRktMTU5VJG51bGzTDQ4PEBESXxAPdHJhaWxpbmdDb250cm9sXmxlYWRpbmdD
            b250cm9sViRjbGFzc4ALgAKAEdQUFRYPFxgZGlhpZGVudGl0eVR0eXBlWGNhdGVnb3J5gAMQARADgArUHB0eDx8gISJZaW50
            ZW50UmVmVGtpbmRVZXh0SWSAAIAIgASACdQkJSYPHygpKl8QEGRldmljZUlkZW50aWZpZXJfEBljb250YWluZXJCdW5kbGVJ
            ZGVudGlmaWVyXxAZZXh0ZW5zaW9uQnVuZGxlSWRlbnRpZmllcoAAgAaABYAHXxA2Y29tLmFwcGxlLkNvbnRyb2xDZW50ZXIu
            Q29udHJvbENlbnRlckNvbnRyb2xzRXh0ZW5zaW9uXxAVY29tLmFwcGxlLnNwcmluZ2JvYXJk0i4vMDFaJGNsYXNzbmFtZVgk
            Y2xhc3Nlc18QFENIU0V4dGVuc2lvbklkZW50aXR5ojIzXxAUQ0hTRXh0ZW5zaW9uSWRlbnRpdHlYTlNPYmplY3RfEEFjb20u
            YXBwbGUuQ29udHJvbENlbnRlci5Db250cm9sQ2VudGVyQ29udHJvbHNFeHRlbnNpb24uZmxhc2hsaWdodNIuLzY3XxASQ0hT
            Q29udHJvbElkZW50aXR5ojgzXxASQ0hTQ29udHJvbElkZW50aXR50i4vOjtfECFQUlF1aWNrQWN0aW9uQ29udHJvbENvbmZp
            Z3VyYXRpb26iPDNfECFQUlF1aWNrQWN0aW9uQ29udHJvbENvbmZpZ3VyYXRpb27UFBUWDz4/GRqADBACgArUHB0eDx9DRCKA
            AIAQgA2ACdQkJSYPH0hJKoAAgA+ADoAHXxApY29tLmFwcGxlLmNhbWVyYS5MYXVuY2hlckNvbnRyb2xFeHRlbnNpb25fEBBj
            b20uYXBwbGUuY2FtZXJhXxAgY29tLmFwcGxlLmNhbWVyYS5kZWVwbGluay5idXR0b27SLi9PUF8QIVBSUG9zdGVyUXVpY2tB
            Y3Rpb25zQ29uZmlndXJhdGlvbqJRM18QIVBSUG9zdGVyUXVpY2tBY3Rpb25zQ29uZmlndXJhdGlvbgAIABEAGgAkACkAMgA3
            AEkATABRAFMAaABuAHUAhwCWAJ0AnwChAKMArAC1ALoAwwDFAMcAyQDLANQA3gDjAOkA6wDtAO8A8QD6AQ0BKQFFAUcBSQFL
            AU0BhgGeAaMBrgG3Ac4B0QHoAfECNQI6Ak8CUgJnAmwCkAKTArcCwALCAsQCxgLPAtEC0wLVAtcC4ALiAuQC5gLoAxQDJwNK
            A08DcwN2AAAAAAAAAgEAAAAAAAAAUgAAAAAAAAAAAAAAAAAAA5o=
            """),
        "com.apple.posterkit.provider.instance.renderingConfiguration.plist":
            b64("""
            YnBsaXN0MDDUAQIDBAUGBwpYJHZlcnNpb25ZJGFyY2hpdmVyVCR0b3BYJG9iamVjdHMSAAGGoF8QD05TS2V5ZWRBcmNoaXZl
            ctEICVRyb290gAGjCwwTVSRudWxs0w0ODxAREF8QFW1vdGlvbkVmZmVjdHNEaXNhYmxlZFYkY2xhc3NfEBNkZXB0aEVmZmVj
            dERpc2FibGVkCIACCNIUFRYXWiRjbGFzc25hbWVYJGNsYXNzZXNfEB5QUlBvc3RlclJlbmRlcmluZ0NvbmZpZ3VyYXRpb26i
            GBlfEB5QUlBvc3RlclJlbmRlcmluZ0NvbmZpZ3VyYXRpb25YTlNPYmplY3QACAARABoAJAApADIANwBJAEwAUQBTAFcAXQBk
            AHwAgwCZAJoAnACdAKIArQC2ANcA2gD7AAAAAAAAAgEAAAAAAAAAGgAAAAAAAAAAAAAAAAAAAQQ=
            """),
        "com.apple.posterkit.provider.instance.titleStyleConfiguration.plist":
            b64("""
            YnBsaXN0MDDUAQIDBAUGBwpYJHZlcnNpb25ZJGFyY2hpdmVyVCR0b3BYJG9iamVjdHMSAAGGoF8QD05TS2V5ZWRBcmNoaXZl
            ctEICVRyb290gAGtCwwrMzQ1PT4/QEFCQ1UkbnVsbN8QDw0ODxAREhMUFRYXGBkaGxwcHh4gHCIjIyUlJygpKl51c2VyQ29u
            ZmlndXJlZF8QImlzQWRhcHRpdmVUaW1lSGVpZ2h0VXNlckNvbmZpZ3VyZWRfEBpwcmVmZXJyZWRUaW1lTWF4WUxhbmRzY2Fw
            ZV8QEWNvbnRlbnRzTHVtaW5lbmNlV3ZlcnNpb25fEBRhbHRlcm5hdGVEYXRlRW5hYmxlZF8QEXByZWZlcnJlZFRpbWVNYXhZ
            WnRpdGxlQ29sb3JfEBN0aW1lTnVtYmVyaW5nU3lzdGVtXxAXcHJlZmVycmVkVGl0bGVBbGlnbm1lbnRfEBRwcmVmZXJyZWRU
            aXRsZUxheW91dFYkY2xhc3NZZ3JvdXBOYW1lXxARdGl0bGVDb250ZW50U3R5bGVfEBV0aW1lRm9udENvbmZpZ3VyYXRpb24I
            CIAJgAmACwiACIAAgACABoAGgAyACoAHgALULC0uGC8wMTJfEBJ0aW1lRm9udElkZW50aWZpZXJcaXNTeXN0ZW1JdGVtVndl
            aWdodIADCYAEgAVfEBhQUlRpbWVGb250SWRlbnRpZmllclNvZnQjQIQAAAAAAADSNjc4OVokY2xhc3NuYW1lWCRjbGFzc2Vz
            XxAjUFJQb3N0ZXJTeXN0ZW1UaW1lRm9udENvbmZpZ3VyYXRpb26jOjs8XxAjUFJQb3N0ZXJTeXN0ZW1UaW1lRm9udENvbmZp
            Z3VyYXRpb25fEB1QUlBvc3RlclRpbWVGb250Q29uZmlndXJhdGlvblhOU09iamVjdBAATxEBYGJwbGlzdDAw1AECAwQFBgcK
            WCR2ZXJzaW9uWSRhcmNoaXZlclQkdG9wWCRvYmplY3RzEgABhqBfEA9OU0tleWVkQXJjaGl2ZXLRCAlUcm9vdIABowsME1Uk
            bnVsbNMNDg8QERJWJGNsYXNzWmZyb3N0TGV2ZWxfEBVwcmVmZXJyZWRNYXRlcmlhbFR5cGWAAiM/6AAAAAAAABAA0hQVFhda
            JGNsYXNzbmFtZVgkY2xhc3Nlc18QI1BSUG9zdGVyQ29udGVudFZpYnJhbnRNYXRlcmlhbFN0eWxlohgZXxAjUFJQb3N0ZXJD
            b250ZW50VmlicmFudE1hdGVyaWFsU3R5bGVYTlNPYmplY3QACAARABoAJAApADIANwBJAEwAUQBTAFcAXQBkAGsAdgCOAJAA
            mQCbAKAAqwC0ANoA3QEDAAAAAAAAAgEAAAAAAAAAGgAAAAAAAAAAAAAAAAAAAQwjP9ALebs/fpUjAAAAAAAAAABdUFJFZGl0
            aW5nTG9vaxAB0jY3REVfEB9QUlBvc3RlclRpdGxlU3R5bGVDb25maWd1cmF0aW9uokY8XxAfUFJQb3N0ZXJUaXRsZVN0eWxl
            Q29uZmlndXJhdGlvbgAIABEAGgAkACkAMgA3AEkATABRAFMAYQBnAIgAlwC8ANkA7QD1AQwBIAErAUEBWwFyAXkBgwGXAa8B
            sAGxAbMBtQG3AbgBugG8Ab4BwAHCAcQBxgHIAcoB0wHoAfUB/AH+Af8CAQIDAh4CJwIsAjcCQAJmAmoCkAKwArkCuwQfBCgE
            MQQ/BEEERgRoBGsAAAAAAAACAQAAAAAAAABHAAAAAAAAAAAAAAAAAAAEjQ==
            """),
    ]

    /// ``files/posterboard/contents.plist`` — the AAR's first member.
    /// ``create_live_photo_files`` wraps this plus the video into
    /// ``segmentation.data.aar``.
    /// The contents.plist ``wrap_in_aar`` embeds beside the video.
    static let livePhotoContentsPlist: Data =
        b64("""
        YnBsaXN0MDDfEBIBAgMEBQYHCAkKCwwNDg8QERITQEFCQ0ROZGV8fYGYvUHOQtNWbGF5b3V0XmNsYXNzaWZpY2F0aW9uWGhh
        c01hdHRlXxAPaW5maWxsQWxnb3JpdGhtV3ZlcnNpb25ebG9jYWxMaWdodERhdGFfEBNsYXlvdXRDb25maWd1cmF0aW9uXxAU
        c2V0dGxpbmdFZmZlY3RTdGF0dXNfEBRzZXR0bGluZ0VmZmVjdExheW91dFpzb3VyY2VNb2RlXXN5c3RlbVZlcnNpb25eaGVh
        ZHJvb21MYXlvdXRWc2NvcmVzV3JlZ2lvbnNdaGFzQmFja2dyb3VuZF8QFHNldHRsaW5nRWZmZWN0Qm91bmRzVHJvbGVdY29s
        b3JBbmFseXNpc9IUFRYXV3ZlcnNpb25YcG9ydHJhaXQQAtkYGRobHB0eHyAhIicuMzQ1Oj1fEBFjbG9ja0ludGVyc2VjdGlv
        bl8QEGRldmljZVJlc29sdXRpb25cdmlzaWJsZUZyYW1lWXRpbWVGcmFtZV8QD2Nsb2NrTGF5ZXJPcmRlcl8QEWhhc1RvcEVk
        Z2VDb250YWN0XWluYWN0aXZlRnJhbWVZaW1hZ2VTaXplXxAPcGFyYWxsYXhQYWRkaW5nEALSIyQlJlVXaWR0aFZIZWlnaHQj
        QIdwAAAAAAAjQJTYAAAAAADUIyQoKSorLC1RWVFYI0CarYY91CfgI0CnublDRjwKI0BR2t00MbWAI0CSAODhFewQ1CMkKCkv
        MDEyI0CW+n87Zi6iI0BwygweuAi2I0Ci5P/PhR/dI0CT2mRiTOivXxAUQ2xvY2tBYm92ZUZvcmVncm91bmQI1CMkKCk2Nzg5
        I0Cbemj9H6P0I0Cob+917r3XI0BR2t00MbWAI0CRmm+BcC4G0iMkOzwjQKegAAAAAAAjQK+AAAAAAADSIyQ+PyNAXZg4E2/J
        7iNAcjZJ5JOP9VVvdGhlchAAEAAQMtVFRkdISUpLTEpNXWxpZ2h0TWFwV2lkdGhebG9jYWxBdXRvVmFsdWVbbGlnaHRNYXBB
        dmdebGlnaHRNYXBIZWlnaHRYbGlnaHRNYXAUAAAAAAAAAAAAAAAAAAAAHyM/xZSvTw2ETkI3V08RB4IUExYUFhMWFRcVFxcY
        GBkZGRwaGxocGx4bHxwhHiEeIR4jHyMeIh4jHSIcIBodJUI1RjNDMkcuQStBME0zUxYUFxUXFRcXGBoZGBocGxwcHxwfHiIe
        Ih4jHiMgJiAlICchKSEnICcgJx8mHSMdRDVJM0QwQi48KzkuRTJRFxYXFxgZGRkaHBsfHCAdIh4kHyQgKSEqISsiKyIpIysj
        LyMrIysjKyIrISkgKCBGNkc1RzJELjwsPStCM08XGBgcGR0bHxwjHSQeJh8nISghKiMrJC4mLyYxJi8mMiYyJjImMCYxJjMl
        LyMuIUE3STZKL0ErPilAMFk4WhgdGh0bIRwmHichKyItIywkMSYyJjMoNyk4KTcqOSo5KzgrOis8KTspNCg2JzQkNTVIL0Er
        PCs9MFE3Yj1eGyEcJR4rISkiMCQ0JjQoNik3KzorOiw9LT8tPy5BL0cuRC5GLkYvQi5BLUErPCk7LDwtPCs7LVAzWTlePV0e
        KyAsIS8jOSc8KDcpQStCLUEuRzFJMUYwSzJQM00zUDNUNVE0UDVSM1AzSjBOLk0pQiY1KD8vUDheNV80WiExIzMmPCg9KUMs
        Ri5QL000VzVaN1c4VzhbOWg6XzpdO2I6XzpiO2I6XjpaOFs2WyZKJTQsUDhiOGI4YDliJkUnRClGK04vVTNbM1w1ZjhjOms9
        bj1oP3I/bT93QnJAhEJ1QndBcT9xQGw/cDxnI2AlOy9UNls7YD1hP2QpRixNLlYyWjhmOGc5bjt1P4Q/fUOKRH1GiEeQSIxJ
        kUebR5pHmUmTRZZHlkSEQnwekiFCK0s1Vj1lPWU/Yy5XM2AzYjdvOm89dkCDRIpDiEmTSqNMlE+cT6NRnE+gVKxRpVSjUKVP
        qVGdTJ9MpDOgITsmTjRYOls+ZT9lM2E3cTpxPX9BikONSpJLl1GnUqVUm1anWbhZtFmrW8FbtlqtW71cwVm7WbRZrFSwQqEh
        PSdMMFU2WTpcOlo3aTx2QHtEhkqJTI9Po1ShV6BZqVutX7NerWCvX69lvWO2Yb1jwWHFYbNhwWGyX7JSsh85I0MrRjJTNWA2
        WDxnQXhGi0qRUpdWlleTW55cmGGkYqtos2i5a7hquGy6bbZvvm29b8NptWq9Z7plt2HIHzckSS1IMlM4UzpcQnZIgU+MVZFZ
        llyWYZxjo2imarJttnGyc7ZytnW0dcF1vHXCdLdzu3W7cbRwu2u7Z7wgNyRCLEkxVTVWNVlKfU6HVoVcoF2ZZptoomuobbBx
        rHW3d7l2tXm4erp5uHnAert6vnq6erx4wXe5dbdyuyF3IzopQytEL04wVU9+V45ckWGYaJ9rqW+ocqt1s3i1erh7unu1fMB/
        wX3Dfb5/vn3Dfb59u32+erl6tne3IYYjOyQ7JkIuTTNLVoZbjV+SaaNtqHGvc6x3q3qxfbx9t4LJgMCCz4XRhdGFzYLNgseC
        x4LFgMOAun23fLYiOCU6Jz0nPCtDLENbj1+SZpZtoXKoeLV6sn2xgLyExYfFh82J0Y3TjdeO2ZPekNmO4o7YiNOIzIbNhMcj
        vSE1JTQoNSY5KDsmPFqQYZlnl3Csd7J8tH+9gsOFy4nSjtuT3pHhk+KW5ZbqmeKW45blld6R3pHdidEXzR4nHy0fKx4vHCYc
        JBsgFBcUGRQYFBkUGhQeFCEWKBQjFSQZQxplFoYUnw/bD+IO4g7lDuYN3Q7bD34bIR4kHSQcIRwfGhwbHBwfHiIgLCArIi8k
        MyUzJjMmNigzJzMmMSgxKTYoNSYuJi8pNys6KTYnNCMuISseJhwjGh0aHBocGhwcIB8iIikjMygyKjouPCs1KzkpOSY0Iysh
        KSAnICshKyQsJS8oOC08LTsrNyYxIywgJh4iHB4cIB4gHiEeKyMwKDMrNy8/LDkpOSUwIy8fKB4lHSMcIR4jICgiLCU0JjYr
        PS5ALT4pNSYyIywgJh8hHiEeJB4kICUlLSgxLTcwPDRDNkMkLh8mHiIcHhshHSIeJCErJC4pOC48Lj0vPS88LDopMyYxJCwj
        KiEnICQiKCIqJCsmMCo4Lz4zQjNBMEEuPRwfHB8dIR4lISoiLSczLDguPTFCMkEuQCs6KTYmMyYvJi0kKiQrIykjKCUtJzAq
        Mys9LzszPzRDMD4tOScyHiMeIyAmIikmMis3LzwwQS09Lz0tPikxJzAlLSMpIyskLCYuJzAnLycwKjYrNi05Mj4zPzA9Kzko
        NSQuICkbHx4iIScjKyYwKzorOSc4KDUmNiMrJCwjLCEnISgiKSIoIyskLCYvKTMtNy48MDsxPi45KTUlLiEmHCAbHBgeGx4c
        IR4kHiIfKB4mHSQeJhwjHCIcIBwgHCAcIBwhHCIcIR4kHiUiKyUvJzQqOCs3KTMlLCIoHyQfIx8kFBMVFBYXFhUXGhcZFxgV
        FhUWFBQVFBUUFRUVFBYXFRUWFRYWFhcXGRkdHCIhJiQrJS0jLSMpIighKCAkHyQQDBANEA0RDhEPEQ4QDRANEAwPDBANEA4Q
        DRANEA0QDRANEA0QDRIPExEUFRgbHCIdIR4gHiIfIx4mHykhKNIUFU9QEALWIFFSU1QUVVhZXl9PW3NjcmVlblNjYWxlXxAQ
        aW5hY3RpdmVUaW1lUmVjdFpzY3JlZW5TaXplWHRpbWVSZWN00iMkVlcjQEoAAAAAAAAjQGAAAAAAAAAjQAAAAAAAAADUIyQo
        KVpbXF0jP+uQCuwz4fYjP7alCZhfLzUjP+i7TGC4OlcjP7G/1E8weCbSIyQlJtQjJCgpYGFiYyM/65AK7DPh9iM/tqUJmF8v
        NSM/6LtMYLg6VyM/sb/UTzB4JhAD0hQVFmbZGBkaGxwdHh8gIWdobTM0c3h50iMkJSbUIyQoKWlqa2wjQJ+68EOM24gjQKw3
        //////8jQGo//5hmZmkjQIIQJ9txqe7UIyQoKW5vcHEjQJtUjsbQBiIjQHP4CTYd7+AjQKdzKpPQ29gjQIZ2iVguf1MI1CMk
        KCl0dXZ3I0CfuvBDjNuII0CsN///////I0BqP/+YZmZpI0CCECfbcanu0iMkOzzSIyR6eyNAYZmF8vNVliNAdalCZhfLzBAB
        o35/gFlpUGhvbmUgT1NWMTguMC4xVzIyQTMzNzDSFBUWgtkYGRobHB0eHyAhg4SJMzSPlJXSIyQlJtQjJCgphYaHiCNAmlyU
        9Wp7mCNAp3G9Ip6HLSNAWOijNdnkACNAkilZhUrCNNQjJCgpiouMjSNAlrTHTOZMayNAcJcbhqauuCNAouXLkeVlRSNAk/1A
        WYzZygjUIyQoKZCRkpMjQJsnChFCKEQjQKglyn1CAP4jQFjoozXZ5AAjQJHEHvde697SIyQ7PNIjJJaXI0BdPm1EIXlnI0Bx
        /wgp7TcF3xAZmZqbnJ2en6ChFKKjpKWmp6ipqqusra6vsLGysrS0skK0tkO0tLS0tLS3srm0tLS6sjRfEBRzZXR0bGluZ0Vm
        ZmVjdExheW91dFxjbG9ja092ZXJsYXBfEBNzZXR0bGluZ0VmZmVjdFZpZGVvXxAYY29uZmlkZW5jZVB1cmVGb3JlZ3JvdW5k
        XxAYY29uZmlkZW5jZVB1cmVCYWNrZ3JvdW5kXxAbc2V0dGxpbmdFZmZlY3RTdGFiaWxpemF0aW9uXxAcc2V0dGxpbmdFZmZl
        Y3RHYXRpbmdGYWlsdXJlc1hncm91bmRlZFRjcm9wXxATbWF0dGVQdXJlQmFja2dyb3VuZF8QE2ZhY2VMb2NhbENvbmZpZGVu
        Y2VWbkZhY2VzXHNlZ21lbnRhdGlvbl8QD2xvY2FsQ29uZmlkZW5jZVhwYXJhbGxheFZsYXlvdXRcZmFjZVBvc2l0aW9uXxAP
        cmVzb2x1dGlvblJhdGlvXWNvbmZpZGVuY2VNYXBfEBNtYXR0ZVB1cmVGb3JlZ3JvdW5kWGZhY2VTaXplXmNsYXNzaWZpY2F0
        aW9uXxAebWV0YWRhdGFDbG9ja092ZXJsYXBBY2NlcHRhYmxlXXVzaW5nSGVhZHJvb20iPwEtbgkJIgAAAAAJIj8h6FIiP1D0
        KQkiP4AAABAFCQjUvr/AwcLHyMlZcHJlZmVycmVkVWZhY2VzVHBldHNaYWNjZXB0YWJsZdQjJCgpw8TFxiM/656AAAAAACM/
        6RWAAAAAACM/xdAAAAAAACM/rpgAAAAAAKCg1CMkKCnKy8zNIz/UKAAAAAAAIz/STAAAAAAAIz/UoAAAAAAAIz/gMAAAAAAA
        1CMkKCnP0NHSIz/sqqqqqqqrIz/sqqqqqqqqIz+qqqpBbBbEIz+qqqqO7u7w2NTV1tfY2doF29zl7u/w+WRfEBNmb3JlZ3Jv
        dW5kTHVtaW5hbmNlXxAQYmFja2dyb3VuZENvbG9yc18QEGZvcmVncm91bmRDb2xvcnNfEBNiYWNrZ3JvdW5kTHVtaW5hbmNl
        WWx1bWluYW5jZVZjb2xvcnNfEA9jbG9ja0FyZWFDb2xvcnMjP9/LF18d5NOi3eGj3t/gIz/edY1B66i9Iz/cVrS5oKWJIz/V
        10jHvBOBo+Lj5CM/5yvHAfDvxiM/5cEv61cWPSM/47+5wb8dWaLm6qPn6OkjP951jUHrqL0jP9xWtLmgpYkjP9XXSMe8E4Gj
        6+ztIz/nK8cB8O/GIz/lwS/rVxY9Iz/jv7nBvx1ZIz/fyxdfHeTTIz/fyxdfHeTTovH1o/Lz9CM/3nWNQeuovSM/3Fa0uaCl
        iSM/1ddIx7wTgaP29/gjP+crxwHw78YjP+XBL+tXFj0jP+O/ucG/HVmh+qP7/P0jP+dWsUA+UEgjP+Xp5cQB5cQjP+PhkqdE
        YjwACAAvADYARQBOAGAAaAB3AI0ApAC7AMYA1ADjAOoA8gEAARcBHAEqAS8BNwFAAUIBVQFpAXwBiQGTAaUBuQHHAdEB4wHl
        AeoB8AH3AgACCQISAhQCFgIfAigCMQI6AkMCTAJVAl4CZwJ+An8CiAKRApoCowKsArECugLDAsgC0QLaAuAC4gLkAuYC8QL/
        Aw4DGgMpAzIDQwNMA08K1QraCtwK6Qr1CwgLEwscCyELKgszCzwLRQtOC1cLYAtpC24LdwuAC4kLkgubC50Logu1C7oLwwvM
        C9UL3gvnC/AL+QwCDAsMFAwVDB4MJwwwDDkMQgxHDEwMVQxeDGAMZAxuDHUMfQyCDJUMmgyjDKwMtQy+DMcM0AzZDOIM6wz0
        DPUM/g0HDRANGQ0iDScNLA01DT4Ncw2KDZcNrQ3IDeMOAQ4gDikOLg5EDloOYQ5uDoAOiQ6QDp0Orw69DtMO3A7rDwwPGg8f
        DyAPIQ8mDycPLA8xDzIPNw85DzoPOw9ED04PVA9ZD2QPbQ92D38PiA+RD5IPkw+cD6UPrg+3D8APyQ/SD9sP5A/tD/4QFBAn
        EDoQUBBaEGEQcxB8EH8QgxCMEJUQnhCiEKsQtBC9EMAQxBDNENYQ3xDjEOwQ9RD+EQcREBETERcRIBEpETIRNhE/EUgRURFT
        EVcRYBFpAAAAAAAAAgEAAAAAAAAA/gAAAAAAAAAAAAAAAAAAEXI=
        """)

    /// The ``1F20C883-EA98-4CCE-9923-0C9A01359721/`` skeleton, paths relative to that root.
    static let livePhotoDescriptor: [String: Data] = [
        "com.apple.posterkit.provider.descriptor.identifier":
            b64("""
            ODhEMUY0NDQtRTJCMy00M0M0LUJCMTUtNzkwQzY3RURFQTU2
            """),
        "providerInfo.plist":
            b64("""
            YnBsaXN0MDDUAQIDBAUGBwpYJHZlcnNpb25ZJGFyY2hpdmVyVCR0b3BYJG9iamVjdHMSAAGGoF8QD05TS2V5ZWRBcmNoaXZl
            ctEICVRyb290gAGjCwwTVSRudWxs0w0ODxAREldOUy5rZXlzWk5TLm9iamVjdHNWJGNsYXNzoKCAAtIUFRYXWiRjbGFzc25h
            bWVYJGNsYXNzZXNcTlNEaWN0aW9uYXJ5ohYYWE5TT2JqZWN0CBEaJCkyN0lMUVNXXWRsd35/gIKHkpuoqwAAAAAAAAEBAAAA
            AAAAABkAAAAAAAAAAAAAAAAAAAC0
            """),
        "versions/0/contents/.com.apple.posterkit.provider.contents.configurableOptions.plist":
            b64("""
            YnBsaXN0MDDUAQIDBAUGBwpYJHZlcnNpb25ZJGFyY2hpdmVyVCR0b3BYJG9iamVjdHMSAAGGoF8QD05TS2V5ZWRBcmNoaXZl
            ctEICVRyb290gAGvEA8LDBccICEpLDA4OUVLTFBVJG51bGzVDQ4PEBESEhQVFl8QIHByZWZlcnJlZEhvbWVTY3JlZW5Db25m
            aWd1cmF0aW9uXxAaZGlzcGxheU5hbWVMb2NhbGl6YXRpb25LZXlWJGNsYXNzXxAfcHJlZmVycmVkVGltZUZvbnRDb25maWd1
            cmF0aW9uc18QFHByZWZlcnJlZFRpdGxlQ29sb3JzgACAAIAOgAKAB9IYDxkbWk5TLm9iamVjdHOhGoADgAbSHQ8eH18QEnRp
            bWVGb250SWRlbnRpZmllcoAEgAVfEBhQUlRpbWVGb250SWRlbnRpZmllclNvZnTSIiMkJVokY2xhc3NuYW1lWCRjbGFzc2Vz
            XxAjUFJQb3N0ZXJTeXN0ZW1UaW1lRm9udENvbmZpZ3VyYXRpb26jJicoXxAjUFJQb3N0ZXJTeXN0ZW1UaW1lRm9udENvbmZp
            Z3VyYXRpb25fEB1QUlBvc3RlclRpbWVGb250Q29uZmlndXJhdGlvblhOU09iamVjdNIiIyorV05TQXJyYXmiKijSGA8tG6Eu
            gAiABtQxDzIzNDU2N15wcmVmZXJyZWRTdHlsZVppZGVudGlmaWVyVWNvbG9ygAyADYAJgApfEBR2aWJyYW50TWF0ZXJpYWxD
            b2xvctY6Ozw9Pg8/QEFCQ0RfEBVVSUNvbG9yQ29tcG9uZW50Q291bnRXVUlXaGl0ZVdVSUFscGhhV05TV2hpdGVcTlNDb2xv
            clNwYWNlEAIiP4AAACI/AAAARTEgMC41EASAC9MiI0ZHSElbJGNsYXNzaGludHNXVUlDb2xvcqJHKKFKV05TQ29sb3IQAtIi
            I01OXVBSUG9zdGVyQ29sb3KiTyhdUFJQb3N0ZXJDb2xvctIiI1FSXxAbUFJQb3N0ZXJDb25maWd1cmFibGVPcHRpb25zolMo
            XxAbUFJQb3N0ZXJDb25maWd1cmFibGVPcHRpb25zAAgAEQAaACQAKQAyADcASQBMAFEAUwBlAGsAdgCZALYAvQDfAPYA+AD6
            APwA/gEAAQUBEAESARQBFgEbATABMgE0AU8BVAFfAWgBjgGSAbgB2AHhAeYB7gHxAfYB+AH6AfwCBQIUAh8CJQInAikCKwIt
            AkQCUQJpAnECeQKBAo4CkAKVApoCoAKiAqQCqwK3Ar8CwgLEAswCzgLTAuEC5ALyAvcDFQMYAAAAAAAAAgEAAAAAAAAAVAAA
            AAAAAAAAAAAAAAAAAzY=
            """),
        "versions/0/contents/0EFB6A0F-7052-4D24-8859-AB22BADF2E93/input.segmentation/asset.resource/contents.plist":
            b64("""
            YnBsaXN0MDDWAQIDBAUGBwgJCgsMWnByb3h5SW1hZ2VYZmlsZVR5cGVZaW1hZ2VGaWxlW29yaWVudGF0aW9uVHR5cGVXdmVy
            c2lvblpwcm94eS5oZWljW3B1YmxpYy5oZWljXUFkanVzdGVkLkhFSUMQBlhBZGp1c3RlZBQAAAAAAAAAAAAAAAAAAAABCBUg
            KTM/RExXY3FzfAAAAAAAAAEBAAAAAAAAAA0AAAAAAAAAAAAAAAAAAACN
            """),
        "versions/0/contents/0EFB6A0F-7052-4D24-8859-AB22BADF2E93/output.layerStack/Contents.json":
            b64("""
            ewogICJ2ZXJzaW9uIiA6IDEwLAogICJsYXllcnMiIDogWwogICAgewogICAgICAiZnJhbWUiIDogewogICAgICAgICJXaWR0
            aCIgOiAxMDQyLjQ1NDYxNDIyMDg3NzQsCiAgICAgICAgIkhlaWdodCIgOiAyODY4LjUyMzA3MTEwNDM4NzMsCiAgICAgICAg
            IlkiIDogLTAuNTIzMDcxMTA0Mzg3MzI3MDcsCiAgICAgICAgIlgiIDogMTc0LjkyNDM1NzAzNDc5NTc4CiAgICAgIH0sCiAg
            ICAgICJmaWxlbmFtZSIgOiAicG9ydHJhaXQtbGF5ZXJfYmFja2dyb3VuZC5IRUlDIiwKICAgICAgInpQb3NpdGlvbiIgOiA1
            LAogICAgICAiaWRlbnRpZmllciIgOiAiYmFja2dyb3VuZCIKICAgIH0sCiAgICB7CiAgICAgICJmcmFtZSIgOiB7CiAgICAg
            ICAgIldpZHRoIiA6IDExODIuNSwKICAgICAgICAiSGVpZ2h0IiA6IDI1NjkuMjUsCiAgICAgICAgIlkiIDogMTQ5LjM3NTAz
            NTEzODkyNDg5LAogICAgICAgICJYIiA6IDY4Ljc0OTk5NTczODI2NzkxMwogICAgICB9LAogICAgICAiZmlsZW5hbWUiIDog
            InBvcnRyYWl0LWxheWVyX3NldHRsaW5nLXZpZGVvLk1PViIsCiAgICAgICJ6UG9zaXRpb24iIDogNSwKICAgICAgImlkZW50
            aWZpZXIiIDogInNldHRsaW5nLXZpZGVvIgogICAgfQogIF0sCiAgInByb3BlcnRpZXMiIDogewogICAgInBvcnRyYWl0TGF5
            b3V0IiA6IHsKICAgICAgImNsb2NrSW50ZXJzZWN0aW9uIiA6IDIsCiAgICAgICJkZXZpY2VSZXNvbHV0aW9uIiA6IHsKICAg
            ICAgICAiV2lkdGgiIDogNzUwLAogICAgICAgICJIZWlnaHQiIDogMTMzNAogICAgICB9LAogICAgICAidmlzaWJsZUZyYW1l
            IiA6IHsKICAgICAgICAiV2lkdGgiIDogODg2LjQzMTc4NDEwNzk0NTg3LAogICAgICAgICJIZWlnaHQiIDogMjU2OS4yNSwK
            ICAgICAgICAiWSIgOiAxNDkuMzc0OTY0ODYxMDc1MDYsCiAgICAgICAgIlgiIDogMjUyLjMxMDA4MjQxMTY4OTY4CiAgICAg
            IH0sCiAgICAgICJ0aW1lRnJhbWUiIDogewogICAgICAgICJXaWR0aCIgOiA3NjMuNTEzMjQzMzc4MzEwNjgsCiAgICAgICAg
            IkhlaWdodCIgOiAyMjcuMjY0OTkyNTAzNzQ4MTIsCiAgICAgICAgIlkiIDogMjEzNS4wNTQ2ODc0OTk3NTUzLAogICAgICAg
            ICJYIiA6IDMxMy43NjkzNTI3NzY1MDcyOAogICAgICB9LAogICAgICAiY2xvY2tMYXllck9yZGVyIiA6ICJDbG9ja0Fib3Zl
            Rm9yZWdyb3VuZCIsCiAgICAgICJoYXNUb3BFZGdlQ29udGFjdCIgOiBmYWxzZSwKICAgICAgImluYWN0aXZlRnJhbWUiIDog
            ewogICAgICAgICJXaWR0aCIgOiA5MTMuMDI0NzM3NjMxMTg0NjIsCiAgICAgICAgIkhlaWdodCIgOiAyNjQ2LjMyNzQ5OTk5
            OTk5OTksCiAgICAgICAgIlkiIDogMTQ5LjM5NjMwNDE0Njc4OTMzLAogICAgICAgICJYIiA6IDIzOS4wMTM2MDU2NTAwNzA0
            MgogICAgICB9LAogICAgICAiaW1hZ2VTaXplIiA6IHsKICAgICAgICAiV2lkdGgiIDogMTMyMCwKICAgICAgICAiSGVpZ2h0
            IiA6IDI4NjgKICAgICAgfSwKICAgICAgInBhcmFsbGF4UGFkZGluZyIgOiB7CiAgICAgICAgIldpZHRoIiA6IDYxLjQ1OTI3
            MDM2NDgxNzU3LAogICAgICAgICJIZWlnaHQiIDogMTUxLjI4NDM1NzgyMTA4OTQ2CiAgICAgIH0KICAgIH0sCiAgICAic2V0
            dGxpbmdFZmZlY3RFbmFibGVkIiA6IHRydWUsCiAgICAiZGVwdGhFbmFibGVkIiA6IGZhbHNlLAogICAgImNsb2NrQXJlYUx1
            bWluYW5jZSIgOiAwLjY0ODc3NjM3OTg3MDEyOTgyLAogICAgInBhcmFsbGF4RGlzYWJsZWQiIDogZmFsc2UKICB9Cn0=
            """),
        "versions/0/contents/0EFB6A0F-7052-4D24-8859-AB22BADF2E93/style.plist":
            b64("""
            PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUv
            L0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+Cjxw
            bGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KCTxrZXk+Y29sb3JTdWdnZXN0aW9uczwva2V5PgoJPGFycmF5Lz4KCTxrZXk+
            a2luZDwva2V5PgoJPHN0cmluZz5PcmlnaW5hbDwvc3RyaW5nPgoJPGtleT5wYXJhbWV0ZXJzPC9rZXk+Cgk8ZGljdD4KCQk8
            a2V5PmNsb2NrQ29sb3I8L2tleT4KCQk8YXJyYXk+CgkJCTxyZWFsPjE8L3JlYWw+CgkJCTxyZWFsPjE8L3JlYWw+CgkJCTxy
            ZWFsPjE8L3JlYWw+CgkJPC9hcnJheT4KCQk8a2V5PmNsb2NrVmlicmFuY3k8L2tleT4KCQk8cmVhbD4wLjA8L3JlYWw+CgkJ
            PGtleT5oZWFkcm9vbUxvb2s8L2tleT4KCQk8aW50ZWdlcj4yPC9pbnRlZ2VyPgoJPC9kaWN0Pgo8L2RpY3Q+CjwvcGxpc3Q+
            Cg==
            """),
        "versions/0/contents/DescriptorModel.plist":
            b64("""
            YnBsaXN0MDDUAQIDBAUGBwpYJHZlcnNpb25ZJGFyY2hpdmVyVCR0b3BYJG9iamVjdHMSAAGGoF8QD05TS2V5ZWRBcmNoaXZl
            ctEICVRyb290gAGpCwwdIjAxMjo9VSRudWxs2A0ODxAREhMUFRYWFhkaGxxWJGNsYXNzXxAUc2h1ZmZsZUNvbmZpZ3VyYXRp
            b25dc3R5bGVDYXRlZ29yeV8QGmRpc3BsYXlOYW1lTG9jYWxpemF0aW9uS2V5VW1lZGlhXmRlc2NyaXB0b3JUeXBlWmlkZW50
            aWZpZXJXdmVyc2lvboAIgACAAIAAgAIQAYAFEADSHg0fIVpOUy5vYmplY3RzoSCAA4AH2CMkDSUmJxQoGyorLBYuHCxec3Vn
            Z2VzdGlvblVVSURZbWVkaWFUeXBlV3N1YnBhdGhfEBFlZGl0Q29uZmlndXJhdGlvbl8QEXN1Z2dlc3Rpb25TdWJ0eXBlWWFz
            c2V0VVVJRIAFEAKABoAEgAARAlyABF8QJDBFRkI2QTBGLTcwNTItNEQyNC04ODU5LUFCMjJCQURGMkU5M18QJDg4RDFGNDQ0
            LUUyQjMtNDNDNC1CQjE1LTc5MEM2N0VERUE1NtIzNDU2WiRjbGFzc25hbWVYJGNsYXNzZXNfEBdQRlBvc3Rlck1lZGlhU3Vn
            Z2VzdGlvbqM3ODlfEBdQRlBvc3Rlck1lZGlhU3VnZ2VzdGlvbl1QRlBvc3Rlck1lZGlhWE5TT2JqZWN00jM0OzxXTlNBcnJh
            eaI7OdIzND4/XxASUEZQb3N0ZXJEZXNjcmlwdG9yokA5XxASUEZQb3N0ZXJEZXNjcmlwdG9yAAgAEQAaACQAKQAyADcASQBM
            AFEAUwBdAGMAdAB7AJIAoAC9AMMA0gDdAOUA5wDpAOsA7QDvAPEA8wD1APoBBQEHAQkBCwEcASsBNQE9AVEBZQFvAXEBcwF1
            AXcBeQF8AX4BpQHMAdEB3AHlAf8CAwIdAisCNAI5AkECRAJJAl4CYQAAAAAAAAIBAAAAAAAAAEEAAAAAAAAAAAAAAAAAAAJ2
            """),
        "versions/0/contents/com.apple.posterkit.provider.contents.galleryOptions":
            b64("""
            YnBsaXN0MDDUAQIDBAUGBwpYJHZlcnNpb25ZJGFyY2hpdmVyVCR0b3BYJG9iamVjdHMSAAGGoF8QD05TS2V5ZWRBcmNoaXZl
            ctEICVRyb290gAGkCwwnKFUkbnVsbN0NDg8QERITFBUWFxgZGhscHR4aIBoiGiAgJl8QGXNwb2tlbk5hbWVMb2NhbGl6YXRp
            b25LZXlccGhvdG9TdWJ0eXBlXxAXZmVhdHVyZWRDb25maWRlbmNlTGV2ZWxfECJhbGxvd3NTeXN0ZW1TdWdnZXN0ZWRDb21w
            bGljYXRpb25zXxAaZGlzcGxheU5hbWVMb2NhbGl6YXRpb25LZXlfEBRtb2R1bGFyQ29tcGxpY2F0aW9uc18QIm9ubHlFbGln
            aWJsZUZvck1hZGVGb3JGb2N1c1NlY3Rpb25fEB5kZXNjcmlwdGl2ZVRleHRMb2NhbGl6YXRpb25LZXlVZm9jdXNfEBJpbmxp
            bmVDb21wbGljYXRpb25UaGVyb18QGHNob3VsZFNob3dBc1NodWZmbGVTdGFja1YkY2xhc3OAABADEAEJgAKAAAiAABAAgAAI
            CIADXxAwUEhPVE9TX1dBTExQQVBFUl9ERVNDUklQVE9SX1RJVExFX0ZFQVRVUkVEX1BIT1RP0ikqKyxaJGNsYXNzbmFtZVgk
            Y2xhc3Nlc18QIUFUWFBvc3RlckRlc2NyaXB0b3JHYWxsZXJ5T3B0aW9uc6ItLl8QIUFUWFBvc3RlckRlc2NyaXB0b3JHYWxs
            ZXJ5T3B0aW9uc1hOU09iamVjdAAIABEAGgAkACkAMgA3AEkATABRAFMAWABeAHkAlQCiALwA4QD+ARUBOgFbAWEBdgF7AZYB
            nQGfAaEBowGkAaYBqAGpAasBrQGvAbABsQGzAeYB6wH2Af8CIwImAkoAAAAAAAACAQAAAAAAAAAvAAAAAAAAAAAAAAAAAAAC
            Uw==
            """),
        "versions/0/contents/com.apple.posterkit.provider.contents.userInfo":
            b64("""
            YnBsaXN0MDDRAQJfEBxzdWdnZXN0aW9uU3VidHlwZURlc2NyaXB0aW9uXxAXV2FsbHBhcGVyIFRvcCBMYW5kc2NhcGUICyoA
            AAAAAAABAQAAAAAAAAADAAAAAAAAAAAAAAAAAAAARA==
            """),
    ]

    /// The ``VideoCAML/`` skeleton for a looping video wallpaper, paths relative to that
    /// root.
    static let videoLoopDescriptor: [String: Data] = [
        "com.apple.posterkit.provider.descriptor.identifier":
            b64("""
            OTE4Mw==
            """),
        "com.apple.posterkit.role.identifier":
            b64("""
            UFJQb3N0ZXJSb2xlTG9ja1NjcmVlbg==
            """),
        "providerInfo.plist":
            b64("""
            YnBsaXN0MDDUAQIDBAUGBwpYJHZlcnNpb25ZJGFyY2hpdmVyVCR0b3BYJG9iamVjdHMSAAGGoF8QD05TS2V5ZWRBcmNoaXZl
            ctEICVRyb290gAGmCwwVFhogVSRudWxs0w0ODxASFFdOUy5rZXlzWk5TLm9iamVjdHNWJGNsYXNzoRGAAqETgAOABV8QHGtD
            b25maWd1cmF0aW9uTGFzdFVzZURhdGVLZXnSFw8YGVdOUy50aW1lI0HGwARI1HUUgATSGxwdHlokY2xhc3NuYW1lWCRjbGFz
            c2VzVk5TRGF0ZaIdH1hOU09iamVjdNIbHCEiXxATTlNNdXRhYmxlRGljdGlvbmFyeaMjJB9fEBNOU011dGFibGVEaWN0aW9u
            YXJ5XE5TRGljdGlvbmFyeQAIABEAGgAkACkAMgA3AEkATABRAFMAWgBgAGcAbwB6AIEAgwCFAIcAiQCLAKoArwC3AMAAwgDH
            ANIA2wDiAOUA7gDzAQkBDQEjAAAAAAAAAgEAAAAAAAAAJQAAAAAAAAAAAAAAAAAAATA=
            """),
        "versions/1/contents/9183.Custom-810w-1080h@2x~ipad.wallpaper/9183.Custom_Floating-810w-1080h@2x~ipad.ca/index.xml":
            b64("""
            PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUv
            L0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+Cjxw
            bGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KCTxrZXk+YXNzZXRNYW5pZmVzdDwva2V5PgoJPHN0cmluZz5hc3NldE1hbmlm
            ZXN0LmNhbWw8L3N0cmluZz4KCTxrZXk+ZG9jdW1lbnRIZWlnaHQ8L2tleT4KCTxyZWFsPjMxNzY8L3JlYWw+Cgk8a2V5PmRv
            Y3VtZW50UmVzaXplc1RvVmlldzwva2V5PgoJPGZhbHNlLz4KCTxrZXk+ZG9jdW1lbnRXaWR0aDwva2V5PgoJPHJlYWw+MzE3
            NjwvcmVhbD4KCTxrZXk+ZHluYW1pY0d1aWRlc0VuYWJsZWQ8L2tleT4KCTx0cnVlLz4KCTxrZXk+Z2VvbWV0cnlGbGlwcGVk
            PC9rZXk+Cgk8ZmFsc2UvPgoJPGtleT5ndWlkZXNFbmFibGVkPC9rZXk+Cgk8dHJ1ZS8+Cgk8a2V5PmludGVyYWN0aXZlTW91
            c2VFdmVudHNFbmFibGVkPC9rZXk+Cgk8dHJ1ZS8+Cgk8a2V5PmludGVyYWN0aXZlU2hvd3NDdXJzb3I8L2tleT4KCTx0cnVl
            Lz4KCTxrZXk+aW50ZXJhY3RpdmVUb3VjaEV2ZW50c0VuYWJsZWQ8L2tleT4KCTxmYWxzZS8+Cgk8a2V5Pmxvb3BFbmQ8L2tl
            eT4KCTxyZWFsPjAuMDwvcmVhbD4KCTxrZXk+bG9vcFN0YXJ0PC9rZXk+Cgk8cmVhbD4wLjA8L3JlYWw+Cgk8a2V5Pmxvb3Bp
            bmdFbmFibGVkPC9rZXk+Cgk8ZmFsc2UvPgoJPGtleT5tdWx0aXRvdWNoRGlzYWJsZXNNb3VzZTwva2V5PgoJPGZhbHNlLz4K
            CTxrZXk+bXVsdGl0b3VjaEVuYWJsZWQ8L2tleT4KCTxmYWxzZS8+Cgk8a2V5PnByZXNlbnRhdGlvbk1vdXNlRXZlbnRzRW5h
            YmxlZDwva2V5PgoJPHRydWUvPgoJPGtleT5wcmVzZW50YXRpb25TaG93c0N1cnNvcjwva2V5PgoJPHRydWUvPgoJPGtleT5w
            cmVzZW50YXRpb25Ub3VjaEV2ZW50c0VuYWJsZWQ8L2tleT4KCTxmYWxzZS8+Cgk8a2V5PnJvb3REb2N1bWVudDwva2V5PgoJ
            PHN0cmluZz5tYWluLmNhbWw8L3N0cmluZz4KCTxrZXk+c2F2ZXNXaW5kb3dGcmFtZTwva2V5PgoJPGZhbHNlLz4KCTxrZXk+
            c2NhbGVzVG9GaXRJblBsYXllcjwva2V5PgoJPGZhbHNlLz4KCTxrZXk+c2hvd3NUb3VjaGVzPC9rZXk+Cgk8dHJ1ZS8+Cgk8
            a2V5PnNuYXBwaW5nRW5hYmxlZDwva2V5PgoJPHRydWUvPgoJPGtleT50aW1lbGluZU1hcmtlcnM8L2tleT4KCTxzdHJpbmc+
            WyhudWxsKV08L3N0cmluZz4KCTxrZXk+dG91Y2hlc0NvbG9yPC9rZXk+Cgk8c3RyaW5nPjEgMSAwIDAuODwvc3RyaW5nPgoJ
            PGtleT51bml0c0luUGl4ZWxzSW5QbGF5ZXI8L2tleT4KCTx0cnVlLz4KPC9kaWN0Pgo8L3BsaXN0Pgo=
            """),
        "versions/1/contents/9183.Custom-810w-1080h@2x~ipad.wallpaper/9183.Custom_Floating-810w-1080h@2x~ipad.ca/main.caml":
            b64("""
            PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KCjxjYW1sIHhtbG5zPSJodHRwOi8vd3d3LmFwcGxlLmNv
            bS9Db3JlQW5pbWF0aW9uLzEuMCI+CiAgPENBTGF5ZXIgYWxsb3dzRWRnZUFudGlhbGlhc2luZz0iMSIgYWxsb3dzR3JvdXBP
            cGFjaXR5PSIxIiBib3VuZHM9IjAgMCAzMTc2IDMxNzYiIGNvbnRlbnRzRm9ybWF0PSJSR0JBOCIgY29ybmVyQ3VydmU9ImNp
            cmN1bGFyIiBoaWRkZW49IjAiIG5hbWU9Il9CQUNLR1JPVU5EIiBwb3NpdGlvbj0iMTU4OCAxNTg4Ij4KICAgIDxzdWJsYXll
            cnM+CiAgICAgIDxDQUxheWVyIGFsbG93c0VkZ2VBbnRpYWxpYXNpbmc9IjEiIGFsbG93c0dyb3VwT3BhY2l0eT0iMSIgYW5j
            aG9yUG9pbnQ9IjAgMCIgYm91bmRzPSIwIDAgMCAwIiBjb250ZW50c0Zvcm1hdD0iUkdCQTgiIGNvcm5lckN1cnZlPSJjaXJj
            dWxhciIgbmFtZT0iX0NFTlRFUl9CQUNLR1JPVU5EIiBwb3NpdGlvbj0iMTU4OCAxNTg4Ii8+CiAgICA8L3N1YmxheWVycz4K
            ICAgIDxzdGF0ZXM+CiAgICAgIDxMS1N0YXRlIG5hbWU9IkxvY2tlZCI+Cgk8ZWxlbWVudHMvPgogICAgICA8L0xLU3RhdGU+
            CiAgICAgIDxMS1N0YXRlIG5hbWU9IlVubG9jayI+Cgk8ZWxlbWVudHMvPgogICAgICA8L0xLU3RhdGU+CiAgICAgIDxMS1N0
            YXRlIG5hbWU9IlNsZWVwIj4KCTxlbGVtZW50cy8+CiAgICAgIDwvTEtTdGF0ZT4KICAgIDwvc3RhdGVzPgogICAgPHN0YXRl
            VHJhbnNpdGlvbnM+CiAgICAgIDxMS1N0YXRlVHJhbnNpdGlvbiBmcm9tU3RhdGU9IioiIHRvU3RhdGU9IlVubG9jayI+Cgk8
            ZWxlbWVudHMvPgogICAgICA8L0xLU3RhdGVUcmFuc2l0aW9uPgogICAgICA8TEtTdGF0ZVRyYW5zaXRpb24gZnJvbVN0YXRl
            PSJVbmxvY2siIHRvU3RhdGU9IioiPgoJPGVsZW1lbnRzLz4KICAgICAgPC9MS1N0YXRlVHJhbnNpdGlvbj4KICAgICAgPExL
            U3RhdGVUcmFuc2l0aW9uIGZyb21TdGF0ZT0iKiIgdG9TdGF0ZT0iTG9ja2VkIj4KCTxlbGVtZW50cy8+CiAgICAgIDwvTEtT
            dGF0ZVRyYW5zaXRpb24+CiAgICAgIDxMS1N0YXRlVHJhbnNpdGlvbiBmcm9tU3RhdGU9IkxvY2tlZCIgdG9TdGF0ZT0iKiI+
            Cgk8ZWxlbWVudHMvPgogICAgICA8L0xLU3RhdGVUcmFuc2l0aW9uPgogICAgICA8TEtTdGF0ZVRyYW5zaXRpb24gZnJvbVN0
            YXRlPSIqIiB0b1N0YXRlPSJTbGVlcCI+Cgk8ZWxlbWVudHMvPgogICAgICA8L0xLU3RhdGVUcmFuc2l0aW9uPgogICAgICA8
            TEtTdGF0ZVRyYW5zaXRpb24gZnJvbVN0YXRlPSJTbGVlcCIgdG9TdGF0ZT0iKiI+Cgk8ZWxlbWVudHMvPgogICAgICA8L0xL
            U3RhdGVUcmFuc2l0aW9uPgogICAgPC9zdGF0ZVRyYW5zaXRpb25zPgogIDwvQ0FMYXllcj4KPC9jYW1sPgo=
            """),
        "versions/1/contents/9183.Custom-810w-1080h@2x~ipad.wallpaper/Wallpaper.plist":
            b64("""
            PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUv
            L0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+Cjxw
            bGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KCTxrZXk+YXBwZWFyYW5jZUF3YXJlPC9rZXk+Cgk8dHJ1ZS8+Cgk8a2V5PmFz
            c2V0czwva2V5PgoJPGRpY3Q+CgkJPGtleT5sb2NrQW5kSG9tZTwva2V5PgoJCTxkaWN0PgoJCQk8a2V5PmRlZmF1bHQ8L2tl
            eT4KCQkJPGRpY3Q+CgkJCQk8a2V5PmJhY2tncm91bmRBbmltYXRpb25GaWxlTmFtZTwva2V5PgoJCQkJPHN0cmluZz45MTgz
            LkN1c3RvbV9CYWNrZ3JvdW5kLTgxMHctMTA4MGhAMnh+aXBhZC5jYTwvc3RyaW5nPgoJCQkJPGtleT5mbG9hdGluZ0FuaW1h
            dGlvbkZpbGVOYW1lS2V5PC9rZXk+CgkJCQk8c3RyaW5nPjkxODMuQ3VzdG9tX0Zsb2F0aW5nLTgxMHctMTA4MGhAMnh+aXBh
            ZC5jYTwvc3RyaW5nPgoJCQkJPGtleT5pZGVudGlmaWVyPC9rZXk+CgkJCQk8aW50ZWdlcj45MTgzPC9pbnRlZ2VyPgoJCQkJ
            PGtleT5uYW1lPC9rZXk+CgkJCQk8c3RyaW5nPkNoaXA8L3N0cmluZz4KCQkJCTxrZXk+dHlwZTwva2V5PgoJCQkJPHN0cmlu
            Zz5MYXllcmVkQW5pbWF0aW9uPC9zdHJpbmc+CgkJCTwvZGljdD4KCQk8L2RpY3Q+Cgk8L2RpY3Q+Cgk8a2V5PmNvbnRlbnRW
            ZXJzaW9uPC9rZXk+Cgk8cmVhbD4yLjAxPC9yZWFsPgoJPGtleT5mYW1pbHk8L2tleT4KCTxzdHJpbmc+Q2hpcDwvc3RyaW5n
            PgoJPGtleT5pZGVudGlmaWVyPC9rZXk+Cgk8aW50ZWdlcj45MTgzPC9pbnRlZ2VyPgoJPGtleT5sb2dpY2FsU2NyZWVuQ2xh
            c3M8L2tleT4KCTxzdHJpbmc+ODEwdy0xMDgwaEAyeH5pcGFkPC9zdHJpbmc+Cgk8a2V5Pm5hbWU8L2tleT4KCTxzdHJpbmc+
            Q2hpcDwvc3RyaW5nPgoJPGtleT5wcmVmZXJyZWRQcm9taW5lbnRDb2xvcjwva2V5PgoJPGRpY3Q+CgkJPGtleT5kYXJrPC9r
            ZXk+CgkJPHN0cmluZz4jMDAwMDA8L3N0cmluZz4KCQk8a2V5PmRlZmF1bHQ8L2tleT4KCQk8c3RyaW5nPiNGRkZGRkY8L3N0
            cmluZz4KCTwvZGljdD4KCTxrZXk+dmVyc2lvbjwva2V5PgoJPGludGVnZXI+MTwvaW50ZWdlcj4KPC9kaWN0Pgo8L3BsaXN0
            Pgo=
            """),
        "versions/1/contents/com.apple.posterkit.provider.contents.userInfo":
            b64("""
            PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUv
            L0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+Cjxw
            bGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KCTxrZXk+cG9zdGVyRW52aXJvbm1lbnRPdmVycmlkZXM8L2tleT4KCTxkYXRh
            PgoJZTMwPQoJPC9kYXRhPgoJPGtleT53YWxscGFwZXJSZXByZXNlbnRpbmdGaWxlTmFtZTwva2V5PgoJPHN0cmluZz45MTgz
            LkN1c3RvbS04MTB3LTEwODBoQDJ4fmlwYWQud2FsbHBhcGVyPC9zdHJpbmc+Cgk8a2V5PndhbGxwYXBlclJlcHJlc2VudGlu
            Z0lkZW50aWZpZXI8L2tleT4KCTxzdHJpbmc+OTk5OTwvc3RyaW5nPgo8L2RpY3Q+CjwvcGxpc3Q+Cg==
            """),
    ]
}
