// Generated by scripts/gen-pb-templates-from-goldennugget.py — do not edit by hand.
//
// Source: ``src/controllers/video_handler.py``, the three string literals ``create_caml`` writes.
// Lifted as source segments, so the placeholder spellings, the attribute order and
// the leading tabs are the reference's own.
//
// `--check` fails on drift, and it also fails if upstream grows a placeholder this
// script does not know about — a literal `{width}` in a caml file is an animation
// that does not load.

import Foundation

/// The fixed halves of a `.ca` bundle's frame list, plus its `index.xml`.
enum PosterBoardTemplates {
    /// The document up to `<values>` — the layer tree, and the keyframe animation
    /// whose `duration`, `calculationMode` and `autoreverses` the caller sets.
    static func camlHeader(width: Int, height: Int, calculationMode: String,
                           duration: Double, reverse: Int) -> String {
        [
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
            "",
            "<caml xmlns=\"http://www.apple.com/CoreAnimation/1.0\">",
            "  <CALayer allowsEdgeAntialiasing=\"1\" allowsGroupOpacity=\"1\" bounds=\"0 0 \(width) \(height)\" contentsFormat=\"RGBA8\" cornerCurve=\"circular\" hidden=\"0\" name=\"_FLOATING\" position=\"\(width / 2) \(height / 2)\">",
            "    <sublayers>",
            "      <CATransformLayer allowsEdgeAntialiasing=\"1\" allowsGroupOpacity=\"1\" allowsHitTesting=\"1\" bounds=\"0 0 \(width) \(height)\" contentsFormat=\"RGBA8\" cornerCurve=\"circular\" name=\"Chip\" position=\"\(width / 2) \(height / 2)\">",
            "\t<sublayers>",
            "\t  <CALayer allowsEdgeAntialiasing=\"1\" allowsGroupOpacity=\"1\" bounds=\"0 0 \(width) \(height)\" contentsFormat=\"RGBA8\" cornerCurve=\"circular\" name=\"CALayer1\" position=\"\(width / 2) \(height / 2)\">",
            "\t    <contents type=\"CGImage\" src=\"assets/0.jpg\"/>",
            "\t    <animations>",
            "\t      <animation type=\"CAKeyframeAnimation\" calculationMode=\"\(calculationMode)\" keyPath=\"contents\" beginTime=\"1e-100\" duration=\"\(duration)\" removedOnCompletion=\"0\" repeatCount=\"inf\" repeatDuration=\"0\" speed=\"1\" timeOffset=\"0\" autoreverses=\"\(reverse)\">",
            "\t\t<values>",
        ].joined(separator: "\n") + "\n"
    }

    /// The closing tags: the three LKStates and their six transitions.
    static func camlFooter() -> String {
        [
            "\t\t</values>",
            "\t      </animation>",
            "\t    </animations>",
            "\t  </CALayer>",
            "\t</sublayers>",
            "      </CATransformLayer>",
            "    </sublayers>",
            "    <states>",
            "      <LKState name=\"Locked\">",
            "\t<elements/>",
            "      </LKState>",
            "      <LKState name=\"Unlock\">",
            "\t<elements/>",
            "      </LKState>",
            "      <LKState name=\"Sleep\">",
            "\t<elements/>",
            "      </LKState>",
            "    </states>",
            "    <stateTransitions>",
            "      <LKStateTransition fromState=\"*\" toState=\"Unlock\">",
            "\t<elements/>",
            "      </LKStateTransition>",
            "      <LKStateTransition fromState=\"Unlock\" toState=\"*\">",
            "\t<elements/>",
            "      </LKStateTransition>",
            "      <LKStateTransition fromState=\"*\" toState=\"Locked\">",
            "\t<elements/>",
            "      </LKStateTransition>",
            "      <LKStateTransition fromState=\"Locked\" toState=\"*\">",
            "\t<elements/>",
            "      </LKStateTransition>",
            "      <LKStateTransition fromState=\"*\" toState=\"Sleep\">",
            "\t<elements/>",
            "      </LKStateTransition>",
            "      <LKStateTransition fromState=\"Sleep\" toState=\"*\">",
            "\t<elements/>",
            "      </LKStateTransition>",
            "    </stateTransitions>",
            "  </CALayer>",
            "</caml>",
        ].joined(separator: "\n") + "\n"
    }

    /// One frame's entry in the `<values>` list.
    static func camlFrame(index: Int) -> String {
        "\t\t\t<CGImage src=\"assets/\(index).jpg\"/>\n"
    }

    /// The `.ca` bundle's `index.xml`, whose `documentWidth`/`documentHeight` are
    /// the frame size — the same numbers as the caml's `bounds`.
    static func camlIndex(width: Int, height: Int) -> String {
        [
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
            "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">",
            "<plist version=\"1.0\">",
            "<dict>",
            "\t<key>assetManifest</key>",
            "\t<string>assetManifest.caml</string>",
            "\t<key>documentHeight</key>",
            "\t<real>\(height)</real>",
            "\t<key>documentResizesToView</key>",
            "\t<true/>",
            "\t<key>documentWidth</key>",
            "\t<real>\(width)</real>",
            "\t<key>dynamicGuidesEnabled</key>",
            "\t<true/>",
            "\t<key>geometryFlipped</key>",
            "\t<false/>",
            "\t<key>guidesEnabled</key>",
            "\t<true/>",
            "\t<key>interactiveMouseEventsEnabled</key>",
            "\t<true/>",
            "\t<key>interactiveShowsCursor</key>",
            "\t<true/>",
            "\t<key>interactiveTouchEventsEnabled</key>",
            "\t<false/>",
            "\t<key>loopEnd</key>",
            "\t<real>0.0</real>",
            "\t<key>loopStart</key>",
            "\t<real>0.0</real>",
            "\t<key>loopingEnabled</key>",
            "\t<false/>",
            "\t<key>multitouchDisablesMouse</key>",
            "\t<false/>",
            "\t<key>multitouchEnabled</key>",
            "\t<false/>",
            "\t<key>presentationMouseEventsEnabled</key>",
            "\t<true/>",
            "\t<key>presentationShowsCursor</key>",
            "\t<true/>",
            "\t<key>presentationTouchEventsEnabled</key>",
            "\t<false/>",
            "\t<key>rootDocument</key>",
            "\t<string>main.caml</string>",
            "\t<key>savesWindowFrame</key>",
            "\t<false/>",
            "\t<key>scalesToFitInPlayer</key>",
            "\t<true/>",
            "\t<key>showsTouches</key>",
            "\t<true/>",
            "\t<key>snappingEnabled</key>",
            "\t<true/>",
            "\t<key>timelineMarkers</key>",
            "\t<string>[(null)]</string>",
            "\t<key>touchesColor</key>",
            "\t<string>1 1 0 0.8</string>",
            "\t<key>unitsInPixelsInPlayer</key>",
            "\t<true/>",
            "</dict>",
            "</plist>",
        ].joined(separator: "\n") + "\n"
    }
}
