// GENERATED FILE — do not edit by hand.
//
// Source of truth: GoldenNugget's `src/tweaks/registry.py` (the tweak
// spec table) and `src/tweaks/basic_plist_locations.py` (the
// `FileLocation` enum).  Regenerate with:
//
//     scripts/gen-tweaks-from-goldennugget.py [--goldennugget <path>]
//
// The port is a generation, not a retype: the table below is emitted from
// the reference module itself, so a tweak added upstream appears here
// without a hand edit and a spec cannot silently drift from the source.

import Foundation

/// An absolute device path a tweak writes to.
///
/// Ported from GoldenNugget's `FileLocation` enum; the raw value is the
/// absolute path, and `TweakDomainMap` turns it into the
/// `(backup domain, relative path)` pair a restorable row needs.
enum TweakFileLocation: String, CaseIterable, Sendable {
    case featureflags = "/var/preferences/FeatureFlags/Global.plist"
    case springboard = "/var/Managed Preferences/mobile/com.apple.springboard.plist"
    case footnote = "/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles/Library/ConfigurationProfiles/SharedDeviceConfiguration.plist"
    case airdrop = "/var/Managed Preferences/mobile/com.apple.sharingd.plist"
    case nanoregistry = "/var/mobile/Library/Preferences/com.apple.NanoRegistry.plist"
    case statusBarOverridesArchive = "/var/mobile/Library/SpringBoard/StatusBarOverrides.archive"
    case globalPreferences = "/var/Managed Preferences/mobile/.GlobalPreferences.plist"
    case globalPreferencesHomeDomain = "/var/mobile/Library/Preferences/.GlobalPreferences.plist"
    case appStore = "/var/Managed Preferences/mobile/com.apple.AppStore.plist"
    case backboardd = "/var/Managed Preferences/mobile/com.apple.backboardd.plist"
    case coreMotion = "/var/Managed Preferences/mobile/com.apple.CoreMotion.plist"
    case pasteboard = "/var/Managed Preferences/mobile/com.apple.Pasteboard.plist"
    case notes = "/var/Managed Preferences/mobile/com.apple.mobilenotes.plist"
    case uikit = "/var/Managed Preferences/mobile/com.apple.UIKit.plist"
    case disabledDaemons = "/var/db/com.apple.xpc.launchd/disabled.plist"
    case screentime = "/var/mobile/Library/Preferences/com.apple.ScreenTimeAgent.plist"
}

/// A tweaks-page section.  Raw values match GoldenNugget's `Section` enum.
enum TweakSection: String, CaseIterable, Identifiable, Sendable {
    case liquidGlass = "Liquid Glass"
    case springboard = "SpringBoard"
    case internalOptions = "Internal Options"
    case daemons = "Daemons to Disable"
    var id: String { rawValue }
}

/// The UI editor a spec wants.  Matches GoldenNugget's `Kind` enum.
enum TweakKind: Sendable {
    case toggle
    case text
    case number
}

/// Every registry-defined tweak, in the reference's own order.
///
/// Iteration order is load-bearing: the compiler merges several tweaks into
/// one plist, and GoldenNugget iterates `tweaks` in this same order, so a
/// later key wins exactly as it does upstream.  Do not sort this array.
enum TweakCatalog {
    static let all: [TweakSpec] = [
        TweakSpec(
            id: "ForceSolariumFallback",
            section: .liquidGlass,
            title: "Force Solarium Fallback",
            location: .globalPreferences,
            key: "SolariumForceFallback",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "26.0",
            maxVersion: "26.99",
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Forces the older Solarium rendering path instead of the newer one. Useful for troubleshooting or for devices where the current Solarium engine misbehaves on iOS 26.",
            multiValues: nil
        ),
        TweakSpec(
            id: "IgnoreSolariumLinkedOnCheck",
            section: .liquidGlass,
            title: "Ignore Solarium Linked-On Check",
            location: .globalPreferences,
            key: "com.apple.SwiftUI.IgnoreSolariumLinkedOnCheck",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "26.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Ignores the compile-time (linked-on) SDK version check for Solarium, allowing Liquid Glass features to run that would otherwise be gated by the SDK an app was built with.",
            multiValues: nil
        ),
        TweakSpec(
            id: "ForceSolariumIntelligence",
            section: .liquidGlass,
            title: "Force Solarium Intelligence",
            location: .globalPreferences,
            key: "SolariumForceIntelligence",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Forces the experimental Solarium 'Intelligence' rendering features (adaptive, machine-driven effects) on iOS 27 where they are not enabled by default.",
            multiValues: nil
        ),
        TweakSpec(
            id: "ForceEnhancedSpeculars",
            section: .liquidGlass,
            title: "Force Enhanced Speculars",
            location: .globalPreferences,
            key: "SolariumForceEnhancedSpeculars",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables the enhanced specular (highlight and reflection) rendering pass that is normally only used on the most capable devices.",
            multiValues: nil
        ),
        TweakSpec(
            id: "UISolariumFallback",
            section: .liquidGlass,
            title: "UI Solarium Fallback",
            location: .globalPreferences,
            key: "UISolariumForceFallback",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Forces UIKit to use the fallback Solarium path when rendering UI. Can fix broken or glitchy system UI on some iOS 27 devices.",
            multiValues: nil
        ),
        TweakSpec(
            id: "IgnoreSolariumHardwareCheck",
            section: .liquidGlass,
            title: "Ignore Solarium Hardware Check",
            location: .globalPreferences,
            key: "com.apple.SwiftUI.IgnoreSolariumHardwareCheck",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Disables the hardware capability check for Solarium, enabling Liquid Glass effects on devices officially considered too weak.",
            multiValues: nil
        ),
        TweakSpec(
            id: "IgnoreSolariumOptOut",
            section: .liquidGlass,
            title: "Ignore Solarium Opt-Out",
            location: .globalPreferences,
            key: "com.apple.SwiftUI.IgnoreSolariumOptOut",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Ignores the system opt-out flag for Solarium, re-enabling Liquid Glass on devices or firmware that have it switched off.",
            multiValues: nil
        ),
        TweakSpec(
            id: "DisallowGlassButtons",
            section: .liquidGlass,
            title: "Disallow Glass Buttons",
            location: .globalPreferences,
            key: "SBDisallowGlassButtons",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Prevents the Liquid Glass material from being applied to system buttons, keeping the old solid button style.",
            multiValues: nil
        ),
        TweakSpec(
            id: "DisallowGlassLockScreen",
            section: .liquidGlass,
            title: "Disallow Glass Lock Screen",
            location: .globalPreferences,
            key: "SBDisallowGlassLockScreen",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Prevents the Liquid Glass material from being applied to the Lock Screen, keeping the old lock screen look.",
            multiValues: nil
        ),
        TweakSpec(
            id: "DisableSpecularEverywhere",
            section: .liquidGlass,
            title: "Disable Specular Everywhere",
            location: .globalPreferences,
            key: "SBDisableSpecularEverywhere",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Disables the specular (glossy reflection) rendering everywhere, removing the shiny glass highlight from Liquid Glass surfaces.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NoLiquidClock",
            section: .liquidGlass,
            title: "Disable Liquid Glass on LS Clock",
            location: .globalPreferences,
            key: "SBDisallowGlassTime",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "26.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Renders the Lock Screen clock in the old solid style instead of with the Liquid Glass / dew effect.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NoLiquidDock",
            section: .liquidGlass,
            title: "Disable Liquid Glass on Dock",
            location: .globalPreferences,
            key: "SBDisableGlassDock",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "26.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Renders the Home Screen dock in the old solid style instead of with the Liquid Glass material.",
            multiValues: nil
        ),
        TweakSpec(
            id: "DisableSpecularMotion",
            section: .liquidGlass,
            title: "Disable Specular Motion",
            location: .globalPreferences,
            key: "SBDisableSpecularEverywhereUsingLSSAssertion",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "26.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Disables the motion-based specular effect on the Lock Screen, so the moving light reflection no longer shifts as you tilt your device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "DisableOuterRefraction",
            section: .liquidGlass,
            title: "Disable Outer Refraction",
            location: .globalPreferences,
            key: "SolariumDisableOuterRefraction",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "26.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Disables the outer refraction (the liquid bending of content at the glass edge) for a cleaner, less distorted look.",
            multiValues: nil
        ),
        TweakSpec(
            id: "DisableSolariumHDR",
            section: .liquidGlass,
            title: "Disable Solarium HDR",
            location: .globalPreferences,
            key: "SolariumAllowHDR",
            value: .bool(false),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "26.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Disables HDR tone-mapping in the Solarium renderer. Can fix washed-out or over-bright Liquid Glass areas. Enabled when the switch is OFF.",
            multiValues: nil
        ),
        TweakSpec(
            id: "DisableWidgetSpecular",
            section: .liquidGlass,
            title: "Disable Widget Specular",
            location: .globalPreferences,
            key: "SBDisableWidgetSpecular",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "26.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Removes the specular (glossy highlight) pass from Home Screen widget icons, so they no longer catch a moving highlight.",
            multiValues: nil
        ),
        TweakSpec(
            id: "DisableDockSpecular",
            section: .liquidGlass,
            title: "Disable Dock Specular",
            location: .globalPreferences,
            key: "SBDisableDockSpecular",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "26.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Removes the specular highlight from the Home Screen dock, leaving the glass material without its glossy sheen.",
            multiValues: nil
        ),
        TweakSpec(
            id: "DisableFolderSpecular",
            section: .liquidGlass,
            title: "Disable Folder Specular",
            location: .globalPreferences,
            key: "SBDisableFolderSpecular",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "26.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Removes the specular highlight from Home Screen folder backgrounds.",
            multiValues: nil
        ),
        TweakSpec(
            id: "ExcludeClearGlassShadows",
            section: .liquidGlass,
            title: "Exclude All Clear Glass Shadows",
            location: .globalPreferences,
            key: "SBExcludeAllClearGlassShadows",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "26.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Drops every shadow the Clear Glass material casts. Useful when the shadows make light wallpapers look muddy.",
            multiValues: nil
        ),
        TweakSpec(
            id: "ExcludeDockShadow",
            section: .liquidGlass,
            title: "Exclude Dock Shadow",
            location: .globalPreferences,
            key: "SBExcludeDockShadow",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "26.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Removes the drop shadow under the Home Screen dock.",
            multiValues: nil
        ),
        TweakSpec(
            id: "ExcludeSearchShadow",
            section: .liquidGlass,
            title: "Exclude Search Shadow",
            location: .globalPreferences,
            key: "SBExcludeSearchShadow",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "26.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Removes the drop shadow under the Home Screen search field.",
            multiValues: nil
        ),
        TweakSpec(
            id: "UseFlatIconsEverywhere",
            section: .liquidGlass,
            title: "Use Flat Icons Everywhere",
            location: .globalPreferences,
            key: "SBUseFlatIconsEverywhere",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "26.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Draws Home Screen icons in the flat style instead of the glass/3D look.",
            multiValues: nil
        ),
        TweakSpec(
            id: "GlassContainerLogging",
            section: .liquidGlass,
            title: "Glass Container Logging",
            location: .globalPreferences,
            key: "com.apple.SwiftUI.GlassContainerLogging",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables glass container debug logging (com.apple.SwiftUI UserDefaults key).",
            multiValues: nil
        ),
        TweakSpec(
            id: "FlexiGlassMacOS",
            section: .liquidGlass,
            title: "Flexi Glass (macOS path)",
            location: .globalPreferences,
            key: "com.apple.SwiftUI.FlexiGlassMacOS",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables FlexiGlass on the macOS-side rendering path (com.apple.SwiftUI UserDefaults key).",
            multiValues: nil
        ),
        TweakSpec(
            id: "FlexiGlassMacOSPointer",
            section: .liquidGlass,
            title: "Flexi Glass (macOS Pointer)",
            location: .globalPreferences,
            key: "com.apple.SwiftUI.FlexiGlassMacOSPointer",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables the pointer variant of FlexiGlass on the macOS-side path (com.apple.SwiftUI UserDefaults key).",
            multiValues: nil
        ),
        TweakSpec(
            id: "InvisibilitySuppressesGlass",
            section: .liquidGlass,
            title: "Invisible View Suppresses Glass",
            location: .globalPreferences,
            key: "com.apple.UIKit.InvisibilitySuppressesGlass",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "When enabled, invisible views suppress the glass effect applied to them (com.apple.UIKit UserDefaults key).",
            multiValues: nil
        ),
        TweakSpec(
            id: "EnableGlassEffectBridgeLayers",
            section: .liquidGlass,
            title: "Enable Glass Effect Bridge Layers",
            location: .globalPreferences,
            key: "EnableGlassEffectBridgeLayers",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables glass effect bridge layers (bare UserDefaults key, read via NSGlobalDomain fallback).",
            multiValues: nil
        ),
        TweakSpec(
            id: "EnableGaussianGlassEffectBridgeLayers",
            section: .liquidGlass,
            title: "Enable Gaussian Glass Bridge Layers",
            location: .globalPreferences,
            key: "EnableGaussianGlassEffectBridgeLayers",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables gaussian glass effect bridge layers (bare UserDefaults key, read via NSGlobalDomain fallback).",
            multiValues: nil
        ),
        TweakSpec(
            id: "UnifiedSystemBackgroundColorsEnabled",
            section: .liquidGlass,
            title: "Unified System Background Colors",
            location: .globalPreferences,
            key: "UnifiedSystemBackgroundColorsEnabled",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables unified system background colors across the system (bare UserDefaults key, read via NSGlobalDomain fallback).",
            multiValues: nil
        ),
        TweakSpec(
            id: "UnaryGlassContainerEnabled",
            section: .liquidGlass,
            title: "Unary Glass Container",
            location: .globalPreferences,
            key: "UnaryGlassContainerEnabled",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables the unary glass container (bare UserDefaults key, read via NSGlobalDomain fallback).",
            multiValues: nil
        ),
        TweakSpec(
            id: "EnableSolariumCompactChrome",
            section: .liquidGlass,
            title: "Enable Solarium Compact Chrome",
            location: .globalPreferences,
            key: "EnableSolariumCompactChrome",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables compact chrome in the Solarium renderer (UIKit debug cluster, bare UserDefaults key).",
            multiValues: nil
        ),
        TweakSpec(
            id: "DisableSolariumCompactChrome",
            section: .liquidGlass,
            title: "Disable Solarium Compact Chrome",
            location: .globalPreferences,
            key: "DisableSolariumCompactChrome",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Disables compact chrome in the Solarium renderer (UIKit debug cluster, bare UserDefaults key).",
            multiValues: nil
        ),
        TweakSpec(
            id: "SolariumIncreasedDiffusion",
            section: .liquidGlass,
            title: "Increased Diffusion",
            location: .globalPreferences,
            key: "SolariumIncreasedDiffusion",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Increases the diffusion / legibility axis of the glass recipe, orthogonal to the tint amount.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SolariumUseDisplayAngle",
            section: .liquidGlass,
            title: "Use Display Angle",
            location: .globalPreferences,
            key: "SolariumUseDisplayAngle",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Uses the display angle to drive glass highlights.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SolariumTintMask",
            section: .liquidGlass,
            title: "Tint Mask",
            location: .globalPreferences,
            key: "SolariumTintMask",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables the Solarium tint mask.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SolariumBackgroundFilter",
            section: .liquidGlass,
            title: "Background Filter",
            location: .globalPreferences,
            key: "SolariumBackgroundFilter",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables the Solarium background filter.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SolariumHighlightWhite",
            section: .liquidGlass,
            title: "Highlight White Point",
            location: .globalPreferences,
            key: "SolariumHighlightWhite",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "White point of the glass highlight (0.0 to 1.0). Defaults to 1.0 (full white). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SolariumLiveTuning",
            section: .liquidGlass,
            title: "Live Tuning",
            location: .globalPreferences,
            key: "SolariumLiveTuning",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables the Solarium live tuning switch — allows real-time glass parameter changes.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SolariumHierarchicalStyle",
            section: .liquidGlass,
            title: "Solarium Hierarchical Style",
            location: .globalPreferences,
            key: "SolariumHierarchicalStyle",
            value: .int(1),
            kind: .number,
            minValue: 0.0,
            maxValue: 10.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Sets the Solarium hierarchical glass style level (integer 0–10). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "GlassHierarchicalStyle",
            section: .liquidGlass,
            title: "Glass Hierarchical Style",
            location: .globalPreferences,
            key: "GlassHierarchicalStyle",
            value: .int(1),
            kind: .number,
            minValue: 0.0,
            maxValue: 10.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Alternative entry for the hierarchical glass style level (integer 0–10). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "GlassVisualDebug",
            section: .liquidGlass,
            title: "Glass Visual Debug",
            location: .globalPreferences,
            key: "GlassVisualDebug",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Overlays glass visual debug information on screen (debug/tuning key).",
            multiValues: nil
        ),
        TweakSpec(
            id: "GlassVisualWarnings",
            section: .liquidGlass,
            title: "Glass Visual Warnings",
            location: .globalPreferences,
            key: "GlassVisualWarnings",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Shows glass visual warnings overlay (debug/tuning key).",
            multiValues: nil
        ),
        TweakSpec(
            id: "BlurFillExperiment",
            section: .liquidGlass,
            title: "Blur Fill Experiment",
            location: .globalPreferences,
            key: "blurFillExperiment",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables the blur fill experiment path (debug/tuning key, exact behavior unknown).",
            multiValues: nil
        ),
        TweakSpec(
            id: "AdaptiveGlassHysteresisDarkRange",
            section: .liquidGlass,
            title: "Adaptive Glass Hysteresis (Dark Range)",
            location: .globalPreferences,
            key: "AdaptiveGlassHysteresisDarkRangeArray",
            value: .string(""),
            kind: .text,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Adaptive glass hysteresis dark range — list of floating-point thresholds. Type inferred as Array<Number>; written as text for this test UI, so may be ignored by the framework. Unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "AdaptiveGlassHysteresisLightRange",
            section: .liquidGlass,
            title: "Adaptive Glass Hysteresis (Light Range)",
            location: .globalPreferences,
            key: "AdaptiveGlassHysteresisLightRangeArray",
            value: .string(""),
            kind: .text,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Adaptive glass hysteresis light range — list of floating-point thresholds. Type inferred as Array<Number>; written as text for this test UI, so may be ignored by the framework. Unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "CalistogaLargeRefraction",
            section: .liquidGlass,
            title: "Large Refraction (Calistoga)",
            location: .globalPreferences,
            key: "CalistogaLargeRefraction",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables the large refraction effect (Calistoga = internal code name for the glass material).",
            multiValues: nil
        ),
        TweakSpec(
            id: "CalistogaRegularClearer",
            section: .liquidGlass,
            title: "Regular Tier Clearer (Calistoga)",
            location: .globalPreferences,
            key: "CalistogaRegularClearer",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Makes the regular tier glass render clearer (Calistoga).",
            multiValues: nil
        ),
        TweakSpec(
            id: "CalistogaBackdropMarginIncludesBlur",
            section: .liquidGlass,
            title: "Backdrop Margin Includes Blur (Calistoga)",
            location: .globalPreferences,
            key: "CalistogaBackdropMarginIncludesBlur",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Backdrop margin calculation includes the blur extent (Calistoga).",
            multiValues: nil
        ),
        TweakSpec(
            id: "CalistogaAllowLumaTracking",
            section: .liquidGlass,
            title: "Allow Luma Tracking (Calistoga)",
            location: .globalPreferences,
            key: "CalistogaAllowLumaTracking",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Allows luminance (luma) tracking to drive glass adaptation (Calistoga).",
            multiValues: nil
        ),
        TweakSpec(
            id: "CalistogaSidebarAccentOpacity",
            section: .liquidGlass,
            title: "Sidebar Accent Opacity (Calistoga)",
            location: .globalPreferences,
            key: "CalistogaSidebarAccentOpacity",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Opacity of the sidebar accent under the glass material (0.0–1.0, Calistoga). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "CalistogaPerceptualBackdropScale",
            section: .liquidGlass,
            title: "Perceptual Backdrop Scale (Calistoga)",
            location: .globalPreferences,
            key: "CalistogaPerceptualBackdropScale",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 2.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Perceptual backdrop scale factor for the glass material (0.0–2.0, Calistoga). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "CalistogaKeyboardGlass",
            section: .liquidGlass,
            title: "Keyboard Glass (Calistoga)",
            location: .globalPreferences,
            key: "CalistogaKeyboardGlass",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Applies the glass material to the keyboard (Calistoga).",
            multiValues: nil
        ),
        TweakSpec(
            id: "CalistogaCameraGlass",
            section: .liquidGlass,
            title: "Camera Glass (Calistoga)",
            location: .globalPreferences,
            key: "CalistogaCameraGlass",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Applies the glass material to the camera surface (Calistoga).",
            multiValues: nil
        ),
        TweakSpec(
            id: "FloatingContentViewSpecularHighlightOpacity",
            section: .liquidGlass,
            title: "Floating Specular Highlight Opacity",
            location: .globalPreferences,
            key: "UISolariumFloatingContentViewSpecularHighlightOpacity",
            value: .double(0.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Opacity of the specular highlight on floating content views (0 = off, 1 = full). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FloatingContentViewUnfocusedBorderOpacity",
            section: .liquidGlass,
            title: "Floating Unfocused Border Opacity",
            location: .globalPreferences,
            key: "UISolariumFloatingContentViewUnfocusedBorderOpacity",
            value: .double(0.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Opacity of the unfocused border on floating content views. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FloatingContentViewUnfocusedBorderWidth",
            section: .liquidGlass,
            title: "Floating Unfocused Border Width",
            location: .globalPreferences,
            key: "UISolariumFloatingContentViewUnfocusedBorderWidth",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 20.0,
            step: 0.5,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Width of the unfocused border on floating content views. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FloatingContentViewEnableBackgroundFills",
            section: .liquidGlass,
            title: "Floating Background Fills",
            location: .globalPreferences,
            key: "UISolariumFloatingContentViewEnableBackgroundFills",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables background fills on floating content views.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FloatingContentViewDebugBackgroundFills",
            section: .liquidGlass,
            title: "Floating Debug Background Fills",
            location: .globalPreferences,
            key: "UISolariumFloatingContentViewDebugBackgroundFills",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables debug background fills on floating content views (debug variant of the above).",
            multiValues: nil
        ),
        TweakSpec(
            id: "FloatingContentViewPunchoutShadow",
            section: .liquidGlass,
            title: "Floating Punchout Shadow",
            location: .globalPreferences,
            key: "UISolariumFloatingContentViewPunchoutShadow",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables punchout shadow on floating content views.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FloatingContentViewModifyTransformMode",
            section: .liquidGlass,
            title: "Floating Transform Mode",
            location: .globalPreferences,
            key: "UISolariumFloatingContentViewModifyTransformMode",
            value: .int(1),
            kind: .number,
            minValue: 0.0,
            maxValue: 10.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Transform mode for floating content view stacking (integer). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FloatingContentViewOverrideRotationX",
            section: .liquidGlass,
            title: "Floating Override Rotation X",
            location: .globalPreferences,
            key: "UISolariumFloatingContentViewOverrideRotationX",
            value: .double(0.0),
            kind: .number,
            minValue: -90.0,
            maxValue: 90.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Forced X-axis rotation for floating content views (degrees). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FloatingContentViewOverrideRotationY",
            section: .liquidGlass,
            title: "Floating Override Rotation Y",
            location: .globalPreferences,
            key: "UISolariumFloatingContentViewOverrideRotationY",
            value: .double(0.0),
            kind: .number,
            minValue: -90.0,
            maxValue: 90.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Forced Y-axis rotation for floating content views (degrees). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FloatingContentViewOverrideTranslationX",
            section: .liquidGlass,
            title: "Floating Override Translation X",
            location: .globalPreferences,
            key: "UISolariumFloatingContentViewOverrideTranslationX",
            value: .double(0.0),
            kind: .number,
            minValue: -1000.0,
            maxValue: 1000.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Forced X-axis translation for floating content views (points). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FloatingContentViewOverrideTranslationY",
            section: .liquidGlass,
            title: "Floating Override Translation Y",
            location: .globalPreferences,
            key: "UISolariumFloatingContentViewOverrideTranslationY",
            value: .double(0.0),
            kind: .number,
            minValue: -1000.0,
            maxValue: 1000.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Forced Y-axis translation for floating content views (points). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FloatingContentViewModifyRotationStrength",
            section: .liquidGlass,
            title: "Floating Rotation Strength",
            location: .globalPreferences,
            key: "UISolariumFloatingContentViewModifyRotationStrength",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Multiplier for the rotation applied to floating content views. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FloatingContentViewModifyTranslationStrength",
            section: .liquidGlass,
            title: "Floating Translation Strength",
            location: .globalPreferences,
            key: "UISolariumFloatingContentViewModifyTranslationStrength",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Multiplier for the translation applied to floating content views. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FocusSpecularHighlightMaxSize",
            section: .liquidGlass,
            title: "Focus Specular Highlight Max Size",
            location: .globalPreferences,
            key: "UISolariumFocusSpecularHighlightMaxSize",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Maximum size of the focus specular highlight (0–1). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FocusSpecularHighlightScaleFactor",
            section: .liquidGlass,
            title: "Focus Specular Highlight Scale Factor",
            location: .globalPreferences,
            key: "UISolariumFocusSpecularHighlightScaleFactor",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 2.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Scale factor of the focus specular highlight. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FocusSpecularHighlightSensitivity",
            section: .liquidGlass,
            title: "Focus Specular Highlight Sensitivity",
            location: .globalPreferences,
            key: "UISolariumFocusSpecularHighlightSensitivity",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Sensitivity of the focus specular highlight to focus changes. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FocusSpecularHighlightNormalizedPositionX",
            section: .liquidGlass,
            title: "Focus Specular Highlight Position X",
            location: .globalPreferences,
            key: "UISolariumFocusSpecularHighlightNormalizedPositionX",
            value: .double(0.5),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Normalized X position of the focus specular highlight (0–1). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "FocusSpecularHighlightNormalizedPositionY",
            section: .liquidGlass,
            title: "Focus Specular Highlight Position Y",
            location: .globalPreferences,
            key: "UISolariumFocusSpecularHighlightNormalizedPositionY",
            value: .double(0.5),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Normalized Y position of the focus specular highlight (0–1). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NewStackedImageRenderingEnabled",
            section: .liquidGlass,
            title: "New Stacked Image Rendering",
            location: .globalPreferences,
            key: "UISolariumNewStackedImageRenderingEnabled",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables the new stacked image rendering pipeline for Home Screen icons (3D parallax layering).",
            multiValues: nil
        ),
        TweakSpec(
            id: "NewStackedImageFiltersEnabled",
            section: .liquidGlass,
            title: "Stacked Image Filters",
            location: .globalPreferences,
            key: "UISolariumNewStackedImageFiltersEnabled",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables image filters in the stacked image rendering pipeline.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NewStackedImage3DTransformsEnabled",
            section: .liquidGlass,
            title: "Stacked Image 3D Transforms",
            location: .globalPreferences,
            key: "UISolariumNewStackedImage3DTransformsEnabled",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables 3D transforms in the stacked image rendering pipeline.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NewStackedImage3DTransformedGlassLayer",
            section: .liquidGlass,
            title: "Stacked Image 3D Glass Layer",
            location: .globalPreferences,
            key: "UISolariumNewStackedImage3DTransformedGlassLayer",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables the 3D-transformed glass layer in the stacked image rendering pipeline.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NewStackedImageSpecularEnabled",
            section: .liquidGlass,
            title: "Stacked Image Specular",
            location: .globalPreferences,
            key: "UISolariumNewStackedImageSpecularEnabled",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables specular highlights on stacked images.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NewStackedImageSpecularOpacity",
            section: .liquidGlass,
            title: "Stacked Image Specular Opacity",
            location: .globalPreferences,
            key: "UISolariumNewStackedImageSpecularOpacity",
            value: .double(0.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Opacity of specular highlights on stacked images (0 = off). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NewStackedImageRadiosityEnabled",
            section: .liquidGlass,
            title: "Stacked Image Radiosity",
            location: .globalPreferences,
            key: "UISolariumNewStackedImageRadiosityEnabled",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables radiosity (color bleed from nearby surfaces) in the stacked image pipeline.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NewStackedImageForceAdjustMotionForSize",
            section: .liquidGlass,
            title: "Stacked Image Adjust Motion for Size",
            location: .globalPreferences,
            key: "UISolariumNewStackedImageForceAdjustMotionForSize",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Forces the stacked image motion adjustment to adapt to icon size.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NewStackedImageForceDefaultScaleSizeIncrease",
            section: .liquidGlass,
            title: "Stacked Image Default Scale Increase",
            location: .globalPreferences,
            key: "UISolariumNewStackedImageForceDefaultScaleSizeIncrease",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Forces the default scale size increase in the stacked image rendering.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NewStackedImageInnerParallaxScale",
            section: .liquidGlass,
            title: "Stacked Image Inner Parallax Scale",
            location: .globalPreferences,
            key: "UISolariumNewStackedImageInnerParallaxScale",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Inner parallax scale of the stacked image (0–1). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NewStackedImageAsymmetricScale",
            section: .liquidGlass,
            title: "Stacked Image Asymmetric Scale",
            location: .globalPreferences,
            key: "UISolariumNewStackedImageAsymmetricScale",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Asymmetric scale of the stacked image (controls non-uniform X/Y scaling). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NewStackedImageProgressiveScale",
            section: .liquidGlass,
            title: "Stacked Image Progressive Scale",
            location: .globalPreferences,
            key: "UISolariumNewStackedImageProgressiveScale",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Progressive scale of the stacked image across depth layers. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NewStackedImageAdditionalTranslation",
            section: .liquidGlass,
            title: "Stacked Image Additional Translation",
            location: .globalPreferences,
            key: "UISolariumNewStackedImageAdditionalTranslation",
            value: .double(0.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 100.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Additional translation applied to stacked images (points). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NewStackedImageFocusedAdditionalScaleAmount",
            section: .liquidGlass,
            title: "Stacked Image Focused Scale Amount",
            location: .globalPreferences,
            key: "UISolariumNewStackedImageFocusedAdditionalScaleAmount",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 2.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Additional scale applied to the focused stacked image. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "StackedImageContainerDefaultMaxDepth",
            section: .liquidGlass,
            title: "Stacked Container Max Depth",
            location: .globalPreferences,
            key: "UISolariumStackedImageContainerDefaultMaxDepth",
            value: .double(20.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 100.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Default maximum depth of the stacked image container (points). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "StackedImageContainerDefaultRotationX",
            section: .liquidGlass,
            title: "Stacked Container Default Rotation X",
            location: .globalPreferences,
            key: "UISolariumStackedImageContainerDefaultRotationX",
            value: .double(0.0),
            kind: .number,
            minValue: -90.0,
            maxValue: 90.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Default X-axis rotation of the stacked image container (degrees). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "StackedImageContainerDefaultRotationY",
            section: .liquidGlass,
            title: "Stacked Container Default Rotation Y",
            location: .globalPreferences,
            key: "UISolariumStackedImageContainerDefaultRotationY",
            value: .double(0.0),
            kind: .number,
            minValue: -90.0,
            maxValue: 90.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Default Y-axis rotation of the stacked image container (degrees). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "StackedImageContainerDefaultTranslationX",
            section: .liquidGlass,
            title: "Stacked Container Default Translation X",
            location: .globalPreferences,
            key: "UISolariumStackedImageContainerDefaultTranslationX",
            value: .double(0.0),
            kind: .number,
            minValue: -1000.0,
            maxValue: 1000.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Default X-axis translation of the stacked image container (points). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "StackedImageContainerDefaultTranslationY",
            section: .liquidGlass,
            title: "Stacked Container Default Translation Y",
            location: .globalPreferences,
            key: "UISolariumStackedImageContainerDefaultTranslationY",
            value: .double(0.0),
            kind: .number,
            minValue: -1000.0,
            maxValue: 1000.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Default Y-axis translation of the stacked image container (points). Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "StackedImageContainerModifyMaxDepthStrength",
            section: .liquidGlass,
            title: "Stacked Container Depth Strength",
            location: .globalPreferences,
            key: "UISolariumStackedImageContainerModifyMaxDepthStrength",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Multiplier for the maximum depth modification of the stacked image container. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "StackedImageContainerModifyRotationStrength",
            section: .liquidGlass,
            title: "Stacked Container Rotation Strength",
            location: .globalPreferences,
            key: "UISolariumStackedImageContainerModifyRotationStrength",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Multiplier for the rotation modification of the stacked image container. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "StackedImageContainerModifyTranslationStrength",
            section: .liquidGlass,
            title: "Stacked Container Translation Strength",
            location: .globalPreferences,
            key: "UISolariumStackedImageContainerModifyTranslationStrength",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Multiplier for the translation modification of the stacked image container. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "StackedImageContainerModifyInnerParallaxScaleStrength",
            section: .liquidGlass,
            title: "Stacked Container Parallax Strength",
            location: .globalPreferences,
            key: "UISolariumStackedImageContainerModifyInnerParallaxScaleStrength",
            value: .double(1.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1.0,
            step: 0.05,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Multiplier for the inner parallax scale modification of the stacked image container. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "StackedImageContainerModifyTransformMinWidth",
            section: .liquidGlass,
            title: "Stacked Container Transform Min Width",
            location: .globalPreferences,
            key: "UISolariumStackedImageContainerModifyTransformMinWidth",
            value: .double(0.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1000.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Minimum width threshold for triggering stacked image container transforms. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "StackedImageContainerModifyTransformMaxWidth",
            section: .liquidGlass,
            title: "Stacked Container Transform Max Width",
            location: .globalPreferences,
            key: "UISolariumStackedImageContainerModifyTransformMaxWidth",
            value: .double(0.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1000.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Maximum width threshold for stacked image container transforms. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "StackedImageContainerModifyTransformMinHeight",
            section: .liquidGlass,
            title: "Stacked Container Transform Min Height",
            location: .globalPreferences,
            key: "UISolariumStackedImageContainerModifyTransformMinHeight",
            value: .double(0.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1000.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Minimum height threshold for triggering stacked image container transforms. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "StackedImageContainerModifyTransformMaxHeight",
            section: .liquidGlass,
            title: "Stacked Container Transform Max Height",
            location: .globalPreferences,
            key: "UISolariumStackedImageContainerModifyTransformMaxHeight",
            value: .double(0.0),
            kind: .number,
            minValue: 0.0,
            maxValue: 1000.0,
            step: 1.0,
            minVersion: "27.0",
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Maximum height threshold for stacked image container transforms. Type inferred; unverified on-device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "LockScreenFootnote",
            section: .springboard,
            title: "Lock Screen Footnote Text",
            location: .footnote,
            key: "LockScreenFootnote",
            value: .string(""),
            kind: .text,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Sets custom text shown at the bottom of the Lock Screen below the time. Long text is cut off — keep it short. Leave empty to remove.",
            multiValues: nil
        ),
        TweakSpec(
            id: "WatchOSCompatibility",
            section: .springboard,
            title: "Allow pairing with any watchOS version",
            location: .nanoregistry,
            key: "",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: true,
            disabled: false,
            detail: "Removes the minimum watchOS pairing check in NanoRegistry so you can pair an Apple Watch running any watchOS version with your iPhone.",
            multiValues: [
                "IOS_PAIRING_EOL_MIN_PAIRING_COMPATIBILITY_VERSION_CHIPIDS": .string(""),
                "maxPairingCompatibilityVersion": .int(37),
                "lastRestoreIdentifier": .string("CD97EEB8-BCD2-486B-BC13-C384E6B916C4"),
                "minPairingCompatibilityVersionWithChipID": .int(1),
                "lastRestoreIdentifier_state": .int(0),
                "AdvertisingIdentifierSeed": .string("85E70251-1960-4DA0-A321-B68AC118FAB5"),
                "minPairingCompatibilityVersion": .int(1),
            ]
        ),
        TweakSpec(
            id: "AirDropDisableTimeLimit",
            section: .springboard,
            title: "Disable AirDrop Time Limit for Everyone Option",
            location: .airdrop,
            key: "OverrideTimeLimitEveryoneMode",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Unlocks the hidden 'Everyone' AirDrop receiving option that would normally be limited to a 10-minute time window.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SBDontLockAfterCrash",
            section: .springboard,
            title: "Disable Lock After Respring",
            location: .springboard,
            key: "SBDontLockAfterCrash",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Prevents the screen from locking right after a respring — the phone won't ask for a passcode immediately after the UI reloads.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SBDontDimOrLockOnAC",
            section: .springboard,
            title: "Disable Screen Dimming While Charging",
            location: .springboard,
            key: "SBDontDimOrLockOnAC",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Stops the display from auto-dimming while the device is connected to a charger.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SBHideLowPowerAlerts",
            section: .springboard,
            title: "Disable Low Battery Alerts",
            location: .springboard,
            key: "SBHideLowPowerAlerts",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Suppresses the 'Low Battery — 20% / 10%' system alerts.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SBHideACPower",
            section: .springboard,
            title: "Hide AC Power on Lock Screen",
            location: .springboard,
            key: "SBHideACPower",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Hides the charging status from the Lock Screen while the device is plugged into AC power.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SBNeverBreadcrumb",
            section: .springboard,
            title: "Disable Breadcrumbs",
            location: .springboard,
            key: "SBNeverBreadcrumb",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Disables the 'Return to <App>' breadcrumb button that appears in the status bar after opening a link from another app.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SBShowSupervisionTextOnLockScreen",
            section: .springboard,
            title: "Show Supervision Text on Lock Screen",
            location: .springboard,
            key: "SBShowSupervisionTextOnLockScreen",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Shows the device-supervision text on the Lock Screen, like the '<Device> is supervised by <org>' label seen on MDM-managed devices.",
            multiValues: nil
        ),
        TweakSpec(
            id: "AirplaySupport",
            section: .springboard,
            title: "Enable AirPlay support for Stage Manager",
            location: .springboard,
            key: "SBExtendedDisplayOverrideSupportForAirPlayAndDontFileRadars",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Adds extended-display AirPlay support for Stage Manager so apps and external displays can use the feature more broadly.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SBMinimumLockscreenIdleTime",
            section: .springboard,
            title: "Auto‑Lock (Lock Screen)",
            location: .springboard,
            key: "SBMinimumLockscreenIdleTime",
            value: .int(5),
            kind: .number,
            minValue: 0.0,
            maxValue: 600.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Sets how many minutes of inactivity before the Lock Screen turns the display off. 0 = never auto-lock.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SBAlwaysShowSystemApertureInSnapshots",
            section: .springboard,
            title: "Show Dynamic Island in Screenshots",
            location: .springboard,
            key: "SBAlwaysShowSystemApertureInSnapshots",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "17.4",
            maxVersion: nil,
            iphoneOnly: true,
            ipadOnly: false,
            disabled: false,
            detail: "Forces the Dynamic Island to appear in screenshots instead of being hidden or shrunk while the screenshot is taken.",
            multiValues: nil
        ),
        TweakSpec(
            id: "HideDICompletely",
            section: .springboard,
            title: "Hide Dynamic Island Completely",
            location: .springboard,
            key: "SBSuppressDynamicIslandCompletely",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: "17.4",
            maxVersion: nil,
            iphoneOnly: true,
            ipadOnly: false,
            disabled: false,
            detail: "Suppresses the Dynamic Island cutout completely so it is never drawn. Can make the screen look odd on devices with a pill cutout.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SBShowAuthenticationEngineeringUI",
            section: .springboard,
            title: "Show Red/Green Authentication Line on Lock Screen",
            location: .springboard,
            key: "SBShowAuthenticationEngineeringUI",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Shows a red/green authentication progress indicator on the Lock Screen while Face ID or passcode checks are running (engineering debug UI).",
            multiValues: nil
        ),
        TweakSpec(
            id: "UseFloatingTabBar",
            section: .springboard,
            title: "Disable Floating Tab Bar",
            location: .uikit,
            key: "UseFloatingTabBar",
            value: .bool(false),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: true,
            disabled: false,
            detail: "Uses the old fixed tab bar style instead of the floating tab bar on iPad. Enabled when the switch is OFF.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SBDisableIconParallax",
            section: .springboard,
            title: "Disable Icon Parallax",
            location: .springboard,
            key: "SBDisableParallax",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Stops Home Screen icons from shifting with the device tilt (the parallax effect). Pair with Disable Icon Page-Control Parallax for a fully static Home Screen.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SBHideSearchAffordance",
            section: .springboard,
            title: "Hide Search Button on Home Screen",
            location: .springboard,
            key: "SBHomeScreenShowsSearchAffordance",
            value: .bool(false),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Removes the search button below the icons on the Home Screen (the faint search bar/icon above the Dock). Enabled when the switch is ON.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SBBuildNumber",
            section: .internalOptions,
            title: "Show Build Version in Status Bar",
            location: .globalPreferences,
            key: "UIStatusBarShowBuildVersion",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Displays the iOS build number (e.g. 21A5284a) in the status bar next to the iOS version.",
            multiValues: nil
        ),
        TweakSpec(
            id: "RTL",
            section: .internalOptions,
            title: "Force Right-to-Left Layout",
            location: .globalPreferences,
            key: "NSForceRightToLeftWritingDirection",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Forces a right-to-left layout for the entire system, mirroring the UI as if your primary language were RTL.",
            multiValues: nil
        ),
        TweakSpec(
            id: "LTR",
            section: .internalOptions,
            title: "Force Left-to-Right Layout",
            location: .globalPreferences,
            key: "NSForceLeftToRightWritingDirection",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Forces a left-to-right layout across the whole system regardless of the RTL language setting.",
            multiValues: nil
        ),
        TweakSpec(
            id: "SBIconVisibility",
            section: .internalOptions,
            title: "Show Hidden Icons on Home Screen",
            location: .globalPreferences,
            key: "SBIconVisibility",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Reveals hidden or disabled Home Screen icons, including internal placeholder icons that are normally not drawn.",
            multiValues: nil
        ),
        TweakSpec(
            id: "iMessageDiagnosticsEnabled",
            section: .internalOptions,
            title: "iMessage Debugging",
            location: .globalPreferences,
            key: "iMessageDiagnosticsEnabled",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables the iMessage engineering debug menu / diagnostics inside the Messages app.",
            multiValues: nil
        ),
        TweakSpec(
            id: "IDSDiagnosticsEnabled",
            section: .internalOptions,
            title: "Continuity Debugging",
            location: .globalPreferences,
            key: "IDSDiagnosticsEnabled",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables the Continuity engineering debug diagnostics in Settings (Apple ID and related sections).",
            multiValues: nil
        ),
        TweakSpec(
            id: "VCDiagnosticsEnabled",
            section: .internalOptions,
            title: "FaceTime Debugging",
            location: .globalPreferences,
            key: "VCDiagnosticsEnabled",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables FaceTime / VoIP engineering debug diagnostics.",
            multiValues: nil
        ),
        TweakSpec(
            id: "AccessoryDeveloperEnabled",
            section: .internalOptions,
            title: "Show Accessory Developer Settings",
            location: .globalPreferences,
            key: "AccessoryDeveloperEnabled",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Adds a hidden Accessory Developer settings page to the Settings app for testing accessories.",
            multiValues: nil
        ),
        TweakSpec(
            id: "DisableSecondsHand",
            section: .internalOptions,
            title: "Disable Clock Icon Seconds Hand",
            location: .globalPreferences,
            key: "SBDisableClockIconSecondsHand",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Stops the animated second hand on the Clock app's Home Screen icon.",
            multiValues: nil
        ),
        TweakSpec(
            id: "DisableSearchingWebsites",
            section: .internalOptions,
            title: "Disable Spotlight Searching in Websites",
            location: .globalPreferences,
            key: "SBSearchDisabledDomains",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Removes website / web search results from Spotlight search suggestions.",
            multiValues: nil
        ),
        TweakSpec(
            id: "ShowButtonHints",
            section: .internalOptions,
            title: "Show Hardware Button Hints in Screenshots",
            location: .globalPreferences,
            key: "SBHardwareButtonHintDropletsAlwaysVisibleInSnapshots",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Shows the side button / action button hint labels in screenshots (engineering debug UI).",
            multiValues: nil
        ),
        TweakSpec(
            id: "AppStoreDebug",
            section: .internalOptions,
            title: "App Store Debug Gesture",
            location: .appStore,
            key: "debugGestureEnabled",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Enables the hidden debug gesture in the App Store app, used to dump store data and inspect the store backend.",
            multiValues: nil
        ),
        TweakSpec(
            id: "NotesDebugMode",
            section: .internalOptions,
            title: "Notes Debug Mode",
            location: .notes,
            key: "DebugModeEnabled",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Turns on the Notes app debug menu for engineering debugging.",
            multiValues: nil
        ),
        TweakSpec(
            id: "BKDigitizerVisualizeTouches",
            section: .internalOptions,
            title: "Show Touches With Debug Info",
            location: .backboardd,
            key: "BKDigitizerVisualizeTouches",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Visually marks every touch point on the screen with debugging information as you touch. Great for diagnosing touch issues.",
            multiValues: nil
        ),
        TweakSpec(
            id: "BKHideAppleLogoOnLaunch",
            section: .internalOptions,
            title: "Hide Respring Icon",
            location: .backboardd,
            key: "BKHideAppleLogoOnLaunch",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Hides the Apple logo animation during respring, showing a black screen instead until the UI comes back.",
            multiValues: nil
        ),
        TweakSpec(
            id: "EnableWakeGestureHaptic",
            section: .internalOptions,
            title: "Vibrate on Raise-to-Wake",
            location: .coreMotion,
            key: "EnableWakeGestureHaptic",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Plays a Taptic Engine vibration when the device wakes via the raise-to-wake gesture.",
            multiValues: nil
        ),
        TweakSpec(
            id: "PlaySoundOnPaste",
            section: .internalOptions,
            title: "Play Sound on Paste",
            location: .pasteboard,
            key: "PlaySoundOnPaste",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Plays a sound every time content is pasted anywhere on the device.",
            multiValues: nil
        ),
        TweakSpec(
            id: "AnnounceAllPastes",
            section: .internalOptions,
            title: "Show Notifications for System Pastes",
            location: .pasteboard,
            key: "AnnounceAllPastes",
            value: .bool(true),
            kind: .toggle,
            minValue: 0.0,
            maxValue: 999.0,
            step: 1.0,
            minVersion: nil,
            maxVersion: nil,
            iphoneOnly: false,
            ipadOnly: false,
            disabled: false,
            detail: "Shows a system notification whenever an app reads the pasteboard, acting as a privacy indicator for system-level pastes.",
            multiValues: nil
        ),
    ]

    /// The daemon groups, appended after the registry rows.  They are not in
    /// `registry.py` upstream -- `gen-daemons-from-goldennugget.py` emits them
    /// from `daemons_tweak.py` -- and they are last so every registry key still
    /// merges into a shared plist before any daemon label does.
    static let allWithDaemons: [TweakSpec] = all + daemonSpecs + [screenTimeSpec]

    static let byID: [String: TweakSpec] =
        Dictionary(uniqueKeysWithValues: allWithDaemons.map { ($0.id, $0) })

    static func inSection(_ section: TweakSection) -> [TweakSpec] {
        all.filter { $0.section == section }
    }
}
