#!/bin/zsh
# Build an unsigned device IPA from the Xcode project (generated by XcodeGen).
# Usage: ./scripts/build-ipa.sh [Debug|Release]   (default: Release)
# Output: build/PoC.ipa (unsigned — sideload via AltStore/SideStore/LiveContainer)
set -euo pipefail
cd "$(dirname "$0")/.."

CONFIG="${1:-Release}"
DERIVED="$(pwd)/build/xderived"

xcodebuild -project PoC.xcodeproj \
  -scheme PoC \
  -configuration "$CONFIG" \
  -destination 'generic/platform=iOS' \
  -derivedDataPath "$DERIVED" \
  CODE_SIGNING_ALLOWED=NO build

APP_PATH="$DERIVED/Build/Products/${CONFIG}-iphoneos/PoC.app"
if [ ! -d "$APP_PATH" ]; then
  echo "error: expected app bundle not found at $APP_PATH" >&2
  exit 1
fi

mkdir -p build
rm -rf build/Payload build/PoC.ipa
mkdir -p build/Payload
cp -R "$APP_PATH" build/Payload/PoC.app
(cd build && zip -qry PoC.ipa Payload && rm -rf Payload)

echo "done: build/PoC.ipa (unsigned, ${CONFIG})"
