#!/usr/bin/env python3
"""Generate Nugget/Core/SkipSetupCatalog.swift from GoldenNugget's pane list.

Why generate instead of retype: the reference keeps the setup-pane list in exactly
one place — ``SKIP_ALL_PANES`` in ``src/restore/skip_setup27.py`` — and says so in
its own comment ("This is the single source of truth for every skip-setup path ...
Keep the list here and never fork a copy").  It is ~80 entries of pure data, and the
port needs the same list that ``build_cloud_config`` puts into
``CloudConfigurationDetails.plist``: a hand-copied array would be a transcription
exercise with 80 chances to drift, and the device compares the pane names literally.

The reference module imports ``cryptography`` and ``pymobiledevice3`` at module
level (for the keybag half of the supervised path), so it is **parsed, not
imported**: ``ast.literal_eval`` on the one assignment is enough for a list of
string literals and needs no reference virtualenv.

Usage:
    scripts/gen-skipsetup-from-goldennugget.py            # write the catalog
    scripts/gen-skipsetup-from-goldennugget.py --check     # exit 1 on drift
    scripts/gen-skipsetup-from-goldennugget.py --goldennugget ~/GoldenNugget
"""

from __future__ import annotations

import argparse
import ast
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "Nugget" / "Core" / "SkipSetupCatalog.swift"
DEFAULT_SOURCE = os.path.expanduser("~/GoldenNugget")
RELATIVE_SOURCE = "src/restore/skip_setup27.py"
LIST_NAME = "SKIP_ALL_PANES"


def read_panes(source: Path) -> list[str]:
    """``SKIP_ALL_PANES`` as a list of strings, parsed rather than executed."""
    path = source / RELATIVE_SOURCE
    if not path.is_file():
        sys.exit(f"gen-skipsetup: no {path}")
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
        if LIST_NAME not in targets:
            continue
        try:
            value = ast.literal_eval(node.value)
        except ValueError as exc:
            sys.exit(f"gen-skipsetup: {LIST_NAME} is not a literal list: {exc}")
        if not isinstance(value, list) or not all(isinstance(v, str) for v in value):
            sys.exit(f"gen-skipsetup: {LIST_NAME} is not a list of strings")
        return value
    sys.exit(f"gen-skipsetup: {LIST_NAME} not found in {path}")


def swift_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def emit(panes: list[str]) -> str:
    # Two entries per line for the same reason the reference wraps its own list:
    # the whole array is data, and a 80-line column of strings is what makes a
    # missing pane visible in a diff.
    body = "\n".join(f'        "{swift_escape(pane)}",' for pane in panes)
    return f"""// Generated by scripts/gen-skipsetup-from-goldennugget.py — do not edit by hand.
//
// Source: the reference's ``{RELATIVE_SOURCE}`` (``{LIST_NAME}``), {len(panes)} panes.
//
// Regenerate after an upstream change to that list; `--check` fails on drift.
// The reference's own comment is the reason this file exists instead of a
// hand-copied array: "This is the single source of truth for every skip-setup
// path ... Keep the list here and never fork a copy."

import Foundation

enum SkipSetupCatalog {{
    /// Every setup pane the reference marks as skipped, in its order.
    ///
    /// The list is the union of its curated iOS 27 list and the older iOS 26 one,
    /// so no pane is lost on either OS; a name a given iOS does not know is a
    /// no-op there.
    static let panes: [String] = [
{body}
    ]
}}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--goldennugget", default=DEFAULT_SOURCE,
                    help="path to the reference checkout (default: ~/GoldenNugget)")
    ap.add_argument("--check", action="store_true",
                    help="report drift and exit 1 instead of writing")
    args = ap.parse_args()

    panes = read_panes(Path(args.goldennugget))
    generated = emit(panes)

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != generated:
            print(f"drift in {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} matches {RELATIVE_SOURCE}")
        return 0

    if OUTPUT.is_file() and OUTPUT.read_text(encoding="utf-8") == generated:
        print(f"{OUTPUT.relative_to(ROOT)} already current ({len(panes)} panes)")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(panes)} panes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
